// Clutch Marks brand mark — the owner's logo tile, generated by
// `.freebuff/build-brand-assets.cjs` into `public/brand/mark-512.png`.
//
// The asset is the logo tile with the wordmark band cropped off, so it can sit
// next to the "Clutch Marks" text in <BrandLockup/> without saying the name
// twice, and so it stays legible at 40px. Regenerate it with that script rather
// than editing the PNG. (This used to be an inline gold tile + graduation-cap
// SVG standing in for a logo that had not been supplied yet.)
import { cn } from "@/lib/utils";

/**
 * The mark on its own. It carries its own tile background and corner rounding,
 * so no extra background or radius is applied here; `tone="outline"` adds a
 * hairline ring for light surfaces where the cream tile would float.
 */
export function BrandMark({
  size = 40,
  tone = "solid",
  className,
}: {
  size?: number;
  tone?: "solid" | "outline";
  className?: string;
}) {
  return (
    <img
      src="/brand/mark-512.png"
      width={size}
      height={size}
      alt=""
      aria-hidden="true"
      decoding="async"
      className={cn(
        "shrink-0 object-contain",
        tone === "outline" && "rounded-[22%] ring-1 ring-border",
        className,
      )}
    />
  );
}

/** Mark + wordmark, for headers and the sidebar. */
export function BrandLockup({
  size = 40,
  subtitle,
  className,
}: {
  size?: number;
  subtitle?: string;
  className?: string;
}) {
  return (
    <div className={cn("flex items-center gap-3 min-w-0", className)}>
      <BrandMark size={size} />
      <div className="min-w-0">
        <p className="font-display text-[17px] font-semibold leading-none tracking-tight text-foreground whitespace-nowrap">
          Clutch Marks
        </p>
        {subtitle && (
          <p className="mt-1 hidden text-[10.5px] uppercase tracking-[0.16em] text-muted-foreground sm:block whitespace-nowrap">
            {subtitle}
          </p>
        )}
      </div>
    </div>
  );
}
