// This file is automatically generated. Do not edit it directly.
//
// Deliberate additions on top of the generated shape (re-apply if this file is
// ever regenerated):
//   * configuration comes from `@/lib/env` so a missing variable is reported
//     instead of silently building a client pointed at `undefined`;
//   * every request is bounded by `fetchWithTimeout`, because a stalled socket
//     used to leave the UI loading forever.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { fetchWithTimeout } from "@/lib/net";
import { SUPABASE_KEY_SAFE, SUPABASE_URL_SAFE } from "@/lib/env";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL_SAFE, SUPABASE_KEY_SAFE, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: fetchWithTimeout,
  },
});
