-- Syllabus currency update (2026-09-30).
--
--   * 0478 (CS OL) and 0625 (Physics OL) are examined 2026–2028; 21 note
--     materials still advertised 2023–2025.
--   * 0478 subject content that the notes never covered: cyber security
--     (vulnerabilities, threats, protection) and digital currency/blockchain.
--   * 0478 subject content that the notes never covered: logic expressions
--     (circuit → expression, truth table → expression, simplification rules).
--   * 0580 subject content that the notes never covered: surds and rationalising
--     denominators. Quick-revision summaries updated to match.
--
-- Generated by .freebuff/gen-syllabus-fix.cjs

update public.study_materials set content = '<h2>Ethics, Security &amp; Impact</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> ethics &amp; professional codes, cyber security threats and protection, malware, online safety, digital currency, environmental/employment impact.</p>

<h3>1. Ethics and codes</h3>
<p>ACM/IEEE-CS/BCS codes: public interest, competence, integrity, privacy. Applying: identify the principle → apply to scenario → stakeholders affected → consequences.</p>

<h3>2. Threats</h3>
<ul>
<li><strong>Malware</strong>: virus (attaches, replicates via host), worm (self-spreads), trojan (disguised), spyware, ransomware.</li>
<li><strong>Social</strong>: phishing (fake emails/sites), pharming (DNS/hosts redirect), shoulder surfing, brute force.</li>
<li><strong>Technical</strong>: interception (packet sniffing), SQL injection (malicious input into queries), DoS (flooding services).</li>
</ul>

<h3>3. Cyber security</h3>
<p>Cyber security protects data, systems and users from attack. A <strong>vulnerability</strong> is a weakness an attack can use; a <strong>threat</strong> is what exploits it.</p>
<ul>
<li><strong>Vulnerabilities</strong>: default or weak passwords, unpatched software, misconfigured access rights, unsecured or public Wi-Fi, removable media (memory sticks), insider threat, unencrypted data in transit.</li>
<li><strong>Malware</strong>: virus (needs a host file and replicates when that file runs), worm (self-spreads across a network), trojan (disguised as useful software), spyware (records activity), ransomware (encrypts files and demands payment), adware.</li>
<li><strong>Social engineering</strong>: phishing (fake email or site asks for details), pharming (malicious redirect via DNS or the hosts file), blagging (invented story), shoulder surfing, brute-force and dictionary attacks.</li>
<li><strong>Technical attacks</strong>: interception / packet sniffing on an unsecured network, SQL injection (malicious input typed into a query field), denial of service and DDoS (flooding a service so it cannot respond), session hijacking.</li>
</ul>
<p><strong>Protection</strong>: strong unique passwords plus 2FA; biometric authentication (fingerprint, face); encryption so intercepted data is unreadable (plaintext is turned into ciphertext with a key — HTTPS/TLS does this on websites); firewalls filtering traffic by IP address and port; anti-malware that scans, blocks and quarantines; patching and updates; user access levels so staff reach only what they need; regular backups; user training; penetration testing to find holes first.</p>
<p><strong>Answer shape:</strong> name the threat precisely (pharming is not phishing), then give the <em>matched</em> defence — pharming → keep DNS servers and hosts files secure and check HTTPS certificates.</p>

<h3>4. Digital currency</h3>
<p>A <strong>digital currency</strong> exists only in electronic form. A <strong>cryptocurrency</strong> (for example Bitcoin) is a decentralised digital currency secured by cryptography and recorded on a <strong>blockchain</strong>.</p>
<ul>
<li><strong>Blockchain</strong>: a distributed ledger — every node holds a copy. Transactions are grouped into blocks, and each block stores the hash of the previous block, so altering an old record breaks the chain and is rejected by the network.</li>
<li><strong>Keys and wallets</strong>: the owner holds a public key (the address others pay to) and a private key (proves ownership and signs a payment). A wallet stores these keys — lose the private key and the money is gone.</li>
<li><strong>Transactions</strong>: broadcast to the network, checked by nodes and added to a block; the verifier (miner) is rewarded. No bank or central authority is involved.</li>
</ul>
<p><strong>Advantages:</strong> quick international transfers, low transaction fees, no central authority to fail or censor, a transparent ledger, and coins cannot be counterfeited. <strong>Disadvantages:</strong> the value is very volatile, payments are irreversible, mining uses large amounts of energy, it appeals to criminals and ransomware demands, it needs internet access and technical care, and there is little consumer protection if a wallet is lost or stolen.</p>

<h3>5. Defences</h3>
<p>Antivirus/antispyware (scan, quarantine), firewalls (port/IP filtering), 2FA + biometrics, strong passwords + managers, encryption (HTTPS, VPN), access levels, patches/updates, user training.</p>

<h3>6. Online behaviour</h3>
<p>Digital footprint, cyberbullying, fake news, privacy settings, verification of sources.</p>

<h3>7. Wider impact</h3>
<p>Employment: automation displaces roles but creates IT jobs. Environment: e-waste, energy use vs paperless efficiency. Monitoring: workplace tracking, CCTV — balance with privacy laws (GDPR-style).</p>

<p><strong>Exam tips:</strong> name the threat precisely (pharming ≠ phishing), then the <em>matched</em> defence; ethics answers need principle + application, not opinion.</p>', updated_at = now() where id = '1ad7eb98-7831-4f23-85f8-9790a66e4ca4';
update public.study_materials set content = '<h2>Logic Gates &amp; Boolean Logic</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> six gates, truth tables, logic expressions, building/describing circuits, problem-to-logic mapping.</p>

<h3>1. The six gates</h3>
<table border="1" cellpadding="6"><tr><th>A</th><th>B</th><th>AND</th><th>OR</th><th>NAND</th><th>NOR</th><th>XOR</th></tr>
<tr><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td></tr>
<tr><td>0</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td></tr>
<tr><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td></tr>
<tr><td>1</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td></tr></table>
<p>NOT inverts. NAND = AND + invert; NOR = OR + invert; XOR = 1 when inputs differ.</p>

<h3>2. Truth tables</h3>
<p>2 inputs → 4 rows; 3 inputs → 8 rows. Work gate by gate, adding intermediate columns for sub-circuit outputs.</p>

<h3>3. Logic expressions</h3>
<p>A Boolean expression describes a circuit in logic: X = A AND NOT B, or X = (A OR B) AND C. Brackets fix the order — work out bracketed parts first, then AND, then OR.</p>
<ul>
<li><strong>Circuit → expression</strong>: label the output of every gate (P, Q, …), write one expression per gate in order, then combine them at the final gate.</li>
<li><strong>Truth table → expression</strong>: mark the rows where the output is 1; for each such row write a term that is true only in that row (write NOT for an input that is 0, AND between the inputs); join the terms with OR. For XOR: X = (NOT A AND B) OR (A AND NOT B).</li>
<li><strong>Expression → truth table</strong>: add an intermediate column for each sub-expression before the output column.</li>
<li><strong>Rules used to simplify</strong>: A AND 1 = A; A AND 0 = 0; A OR 1 = 1; A OR 0 = A; A AND A = A; A AND NOT A = 0; A OR NOT A = 1; NOT(NOT A) = A; X OR (X AND Y) = X. (AS extension, 9618: De Morgan''s laws — NOT(A AND B) = NOT A OR NOT B and NOT(A OR B) = NOT A AND NOT B.)</li>
</ul>
<p><strong>Example:</strong> a light X is on only when switch A is on and switch B is off → X = A AND NOT B, so X = 1 in exactly one row of its truth table (A = 1, B = 0).</p>

<h3>4. Problem → logic</h3>
<p>Define inputs/outputs first. Alarm rings (X=1) if sensor P triggered AND (door D OR window W): X = P AND (D OR W). Then draw the circuit: OR first, then AND.</p>

<h3>5. Describing circuits</h3>
<p>Write the expression from a diagram gate by gate; annotate output of each gate (X, Y) before combining.</p>

<p><strong>Exam tips:</strong> check your truth table row count before writing; in problem questions, state "input P = 1 means sensor triggered" — definitions earn marks.</p>', updated_at = now() where id = '410f9140-4fa3-467e-8cac-852bafc28653';
update public.study_materials set content = '<h2>Number — Indices and Standard Form</h2>
<p><strong>Cambridge IGCSE 0580 (2025–2027):</strong> index laws, negative and fractional indices, standard form arithmetic, surds and rationalising denominators.</p>

<h3>1. Index laws</h3>
<ul>
<li>aᵐ × aⁿ = aᵐ⁺ⁿ; aᵐ ÷ aⁿ = aᵐ⁻ⁿ; (aᵐ)ⁿ = aᵐⁿ</li>
<li>a⁰ = 1; a⁻ⁿ = 1/aⁿ; a^(1/n) = ⁿ√a; a^(m/n) = (ⁿ√a)ᵐ</li>
</ul>
<p><strong>Examples:</strong> 27^(2/3) = (³√27)² = 9; 5⁻² = 1/25; (2x³)² = 4x⁶.</p>

<h3>2. Standard form</h3>
<p>a × 10ⁿ with 1 ≤ a &lt; 10.</p>
<ul>
<li>47 382 = 4.7382 × 10⁴; 0.0056 = 5.6 × 10⁻³</li>
<li>Multiplication: multiply a''s, add powers. Division: divide a''s, subtract powers.</li>
</ul>
<p><strong>Example:</strong> (3 × 10⁵) × (4 × 10⁻²) = 12 × 10³ = 1.2 × 10⁴.</p>

<h3>3. Calculator use</h3>
<p>Use the ×10ˣ key, not 10 ^; keep working in standard form and convert at the end. Give final answers in the form asked (often 3 s.f. standard form).</p>

<h3>4. Solving index equations</h3>
<p>Match bases: 2ˣ = 32 ⇒ 2ˣ = 2⁵ ⇒ x = 5. With different bases, rewrite (8 = 2³).</p>

<h3>5. Surds</h3>
<p>A <strong>surd</strong> is a root that cannot be written as a rational number: √2, √3, 3√5.</p>
<ul>
<li><strong>Rules</strong>: √a × √b = √(ab); √a ÷ √b = √(a/b); (√a)² = a.</li>
<li><strong>Simplify</strong> by taking out the largest square factor: √50 = √25 × √2 = 5√2; √72 = 6√2; √(9/16) = 3/4.</li>
<li><strong>Add and subtract like surds</strong>: √18 + √8 = 3√2 + 2√2 = 5√2. Unlike surds cannot be combined: 2√3 + √5 stays as it is.</li>
<li><strong>Rationalise the denominator</strong> so no root is left below the line: 6/√3 = 6√3/3 = 2√3; 1/(3 + √2) = (3 − √2) / ((3 + √2)(3 − √2)) = (3 − √2)/7 — multiply top and bottom by the <em>conjugate</em>.</li>
<li><strong>Expanding</strong>: (2 + √3)(2 − √3) = 4 − 3 = 1; difference of two squares clears the surd.</li>
</ul>
<p><strong>Example:</strong> write √12 + √75 in the form k√3 → 2√3 + 5√3 = 7√3.</p>

<p><strong>Exam tips:</strong> check a is in [1, 10) before writing standard form; in "multiply out" questions apply the power to <em>every</em> factor including coefficients.</p>', updated_at = now() where id = 'e1c1569d-a45c-4ebe-8012-6df10e500034';
update public.study_materials set content = '<h2>Quick revision: Ethics, Security & Impact</h2>
<p><strong>Computer Science — OL.</strong> ethics &amp; professional codes, cyber security threats and protection, malware, online safety, digital currency, environmental/employment impact.</p>
<ul>
<li>1. Ethics and codes</li>
<li>2. Threats</li>
<li>3. Cyber security</li>
<li>4. Digital currency</li>
<li>5. Defences</li>
<li>6. Online behaviour</li>
<li>7. Wider impact</li>
</ul>
<p><strong>How to use this:</strong> skim the list above, then open the full revision notes for any area that feels shaky, and finish with the topic questions to check yourself.</p>', updated_at = now() where id = '1cbe3f90-97ce-4f84-8928-e7f861cadf0e';
update public.study_materials set content = '<h2>Quick revision: Logic Gates & Boolean Logic</h2>
<p><strong>Computer Science — OL.</strong> six gates, truth tables, logic expressions, building/describing circuits, problem-to-logic mapping.</p>
<ul>
<li>1. The six gates</li>
<li>2. Truth tables</li>
<li>3. Logic expressions</li>
<li>4. Problem → logic</li>
<li>5. Describing circuits</li>
</ul>
<p><strong>How to use this:</strong> skim the list above, then open the full revision notes for any area that feels shaky, and finish with the topic questions to check yourself.</p>', updated_at = now() where id = 'b6a60bd2-bb48-4e1a-a466-d85e083f3864';
update public.study_materials set content = '<h2>Quick revision: Number — Indices and Standard Form</h2>
<p><strong>Mathematics — OL.</strong> index laws, negative and fractional indices, standard form arithmetic, surds.</p>
<ul>
<li>1. Index laws</li>
<li>2. Standard form</li>
<li>3. Calculator use</li>
<li>4. Solving index equations</li>
<li>5. Surds</li>
</ul>
<p><strong>How to use this:</strong> skim the list above, then open the full revision notes for any area that feels shaky, and finish with the topic questions to check yourself.</p>', updated_at = now() where id = '9fe2f14b-5551-4243-bd1c-cc87b02ee427';
update public.study_materials set content = '<h2>Algorithms &amp; Programming</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> pseudocode, flowcharts, standard algorithms (linear/bubble), trace tables, validation &amp; verification.</p>

<h3>1. Pseudocode</h3>
<pre>OUTPUT "Enter n"
INPUT n
IF n MOD 2 = 0 THEN
  OUTPUT "even"
ELSE
  OUTPUT "odd"
ENDIF

FOR i ← 1 TO 10
  total ← total + i
NEXT i

WHILE total < 100
  total ← total + n
ENDWHILE

FUNCTION square(x : INTEGER) RETURNS INTEGER
  RETURN x * x
ENDFUNCTION</pre>
<p>Assignment ←, comparison =, MOD/DIV for remainders/quotients.</p>

<h3>2. Flowchart symbols</h3>
<p>Terminator (oval), process (rectangle), decision (diamond), input/output (parallelogram), flow lines with arrows.</p>

<h3>3. Standard algorithms</h3>
<ul>
<li>Linear search: check each item until found/end — works unsorted.</li>
<li>Bubble sort: repeated adjacent swaps; largest bubbles to the end each pass; n−1 passes max; early exit when no swaps.</li>
<li>Counting/totaling patterns; max/min with a running best value.</li>
</ul>

<h3>4. Trace tables</h3>
<p>One column per variable; log every assignment in order; watch loop counters and reassignments.</p>
<pre>x ← 1; total ← 0
WHILE x <= 4
  total ← total + x * 2
  x ← x + 1
ENDWHILE  // total = 20</pre>

<h3>5. Validation vs verification</h3>
<ul>
<li><strong>Validation</strong>: automatic checks on data — range (exam mark 0–100), length (password ≥ 8), type, format (postcode pattern), presence (field not empty), check digit (barcode).</li>
<li><strong>Verification</strong>: data matches the source — double entry, visual/proof reading.</li>
</ul>

<h3>6. Testing</h3>
<p>Normal (typical), abnormal (rejects invalid), boundary (extremes just inside/outside). Test data tables list input → expected output.</p>

<p><strong>Exam tips:</strong> write pseudocode with ENDIF/NEXT/ENDWHILE terminators; in trace tables record the condition result too; boundary choices need "just above/below/at" values.</p>', updated_at = now() where id = '230d770c-b169-4153-b7a0-41297244195b';
update public.study_materials set content = '<h2>Hardware &amp; Architecture</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> von Neumann model, FDE cycle, registers, buses, RAM/ROM, secondary storage, embedded systems.</p>

<h3>1. Von Neumann model</h3>
<p>CPU (ALU, control unit, registers) + memory + I/O on shared buses; instructions stored as data (stored program concept).</p>

<h3>2. Registers</h3>
<table border="1" cellpadding="6"><tr><th>Register</th><th>Role</th></tr>
<tr><td>PC</td><td>address of next instruction</td></tr>
<tr><td>MAR</td><td>address being read/written</td></tr>
<tr><td>MDR</td><td>data/instruction in transit</td></tr>
<tr><td>ACC</td><td>ALU results accumulator</td></tr></table>

<h3>3. FDE cycle</h3>
<p>Fetch: PC → MAR; memory → MDR → CIR; PC + 1. Decode: control unit interprets opcode. Execute: ALU/registers act. Interrupts can pause between cycles.</p>

<h3>4. Buses and performance</h3>
<p>Address bus (one-way, width ⇒ addressable memory), data bus (two-way, width ⇒ bits per transfer), control bus. Performance factors: clock speed, cache size, core count — explain the effect, not just the name.</p>

<h3>5. RAM vs ROM</h3>
<p>RAM: volatile, read/write, holds running programs + data. ROM: non-volatile, read-only, bootstrap/firmware. Embedded systems: dedicated microprocessors inside devices (washing machines, engines) — one function, low cost, hard to update.</p>

<h3>6. Secondary storage</h3>
<ul>
<li><strong>Magnetic (HDD)</strong>: platters, read/write heads; high capacity, cheap per GB, moving parts (shock-sensitive).</li>
<li><strong>Optical (CD/DVD/Blu-ray)</strong>: laser pits/lands; cheap, portable, slow, small capacity.</li>
<li><strong>Solid state (SSD/flash)</strong>: NAND cells; fast, silent, robust, no moving parts, more expensive per GB, finite write cycles.</li>
</ul>
<p>Choose by use case: video editing (SSD), archive (optical/magnetic), tablets (flash).</p>

<p><strong>Exam tips:</strong> trace FDE with register values; compare storage on capacity, speed, cost, durability, portability; always tie a performance factor to its <em>effect</em>.</p>', updated_at = now() where id = 'fc1ffd6d-f913-4c5a-9336-ec908c9223ec';
update public.study_materials set content = '<h2>Database Systems</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> limitations of file-based systems; relational concepts; SQL (SELECT, FROM, WHERE, ORDER BY, GROUP BY, INNER JOIN, SUM, COUNT); DBMS features.</p>

<h3>1. File-based problems</h3>
<p>Data repetition (wasted space, inconsistency), fixed queries, no concurrent access control — solved by a DBMS with shared, structured tables.</p>

<h3>2. Relational concepts</h3>
<ul>
<li>Table, record, field; primary key (unique); secondary key (indexed search field); foreign key links tables.</li>
<li>One-to-many relationships via foreign keys; no repeating groups (1NF mindset).</li>
</ul>

<h3>3. SQL</h3>
<pre>SELECT Title, Year FROM Films
WHERE Genre = ''Sci-Fi'' AND Year > 2015
ORDER BY Year DESC;

SELECT Genre, COUNT(*) AS NumFilms, SUM(Rating) AS TotalRating
FROM Films
GROUP BY Genre;

SELECT s.Name, f.Title
FROM Students s INNER JOIN Loans l ON s.StudentID = l.StudentID
INNER JOIN Films f ON l.FilmID = f.FilmID;</pre>
<p>WHERE filters rows; GROUP BY aggregates; JOIN combines on matching keys.</p>

<h3>4. DBMS features</h3>
<p>Data dictionary (schema, types, constraints), query processor, forms/reports, access rights (read/write per user), data integrity (validation rules), backup/recovery.</p>

<p><strong>Exam tips:</strong> write SQL keywords uppercase; alias joined tables (s, l, f); when asked "why relational", cite reduced redundancy + flexible queries.</p>', updated_at = now() where id = 'e57fcf07-484e-4716-b79e-2e80f4c59824';
update public.study_materials set content = '<h2>Ethics, Security &amp; Impact</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> ethics &amp; professional codes, security threats, malware, online safety, environmental/employment impact.</p>

<h3>1. Ethics and codes</h3>
<p>ACM/IEEE-CS/BCS codes: public interest, competence, integrity, privacy. Applying: identify the principle → apply to scenario → stakeholders affected → consequences.</p>

<h3>2. Threats</h3>
<ul>
<li><strong>Malware</strong>: virus (attaches, replicates via host), worm (self-spreads), trojan (disguised), spyware, ransomware.</li>
<li><strong>Social</strong>: phishing (fake emails/sites), pharming (DNS/hosts redirect), shoulder surfing, brute force.</li>
<li><strong>Technical</strong>: interception (packet sniffing), SQL injection (malicious input into queries), DoS (flooding services).</li>
</ul>

<h3>3. Defences</h3>
<p>Antivirus/antispyware (scan, quarantine), firewalls (port/IP filtering), 2FA + biometrics, strong passwords + managers, encryption (HTTPS, VPN), access levels, patches/updates, user training.</p>

<h3>4. Online behaviour</h3>
<p>Digital footprint, cyberbullying, fake news, privacy settings, verification of sources.</p>

<h3>5. Wider impact</h3>
<p>Employment: automation displaces roles but creates IT jobs. Environment: e-waste, energy use vs paperless efficiency. Monitoring: workplace tracking, CCTV — balance with privacy laws (GDPR-style).</p>

<p><strong>Exam tips:</strong> name the threat precisely (pharming ≠ phishing), then the <em>matched</em> defence; ethics answers need principle + application, not opinion.</p>', updated_at = now() where id = '1ad7eb98-7831-4f23-85f8-9790a66e4ca4';
update public.study_materials set content = '<h2>Logic Gates &amp; Boolean Logic</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> six gates, truth tables, building/describing circuits, problem-to-logic mapping.</p>

<h3>1. The six gates</h3>
<table border="1" cellpadding="6"><tr><th>A</th><th>B</th><th>AND</th><th>OR</th><th>NAND</th><th>NOR</th><th>XOR</th></tr>
<tr><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td></tr>
<tr><td>0</td><td>1</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td></tr>
<tr><td>1</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>1</td></tr>
<tr><td>1</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td></tr></table>
<p>NOT inverts. NAND = AND + invert; NOR = OR + invert; XOR = 1 when inputs differ.</p>

<h3>2. Truth tables</h3>
<p>2 inputs → 4 rows; 3 inputs → 8 rows. Work gate by gate, adding intermediate columns for sub-circuit outputs.</p>

<h3>3. Problem → logic</h3>
<p>Define inputs/outputs first. Alarm rings (X=1) if sensor P triggered AND (door D OR window W): X = P AND (D OR W). Then draw the circuit: OR first, then AND.</p>

<h3>4. Describing circuits</h3>
<p>Write the expression from a diagram gate by gate; annotate output of each gate (X, Y) before combining.</p>

<p><strong>Exam tips:</strong> check your truth table row count before writing; in problem questions, state "input P = 1 means sensor triggered" — definitions earn marks.</p>', updated_at = now() where id = '410f9140-4fa3-467e-8cac-852bafc28653';
update public.study_materials set content = '<h2>Forces &amp; Motion</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> motion (speed, acceleration, graphs); mass &amp; weight; density link; force basics (F = ma, resultant); momentum (Extended); turning effects; equilibrium.</p>

<h3>1. Kinematics</h3>
<ul>
<li>Speed = distance/time; average speed = (u + v)/2 for uniform acceleration.</li>
<li>Acceleration a = (v − u)/t.</li>
<li>SUVAT (uniform a): v = u + at; s = ut + ½at²; v² = u² + 2as.</li>
</ul>

<h3>2. Motion graphs</h3>
<ul>
<li>Distance–time: gradient = speed.</li>
<li>Speed–time: gradient = acceleration; area = distance. Negative gradient = deceleration.</li>
<li>Free fall 1: g ≈ 9.8 m/s² (use 10) — v = gt from rest.</li>
</ul>

<h3>3. Mass, weight, density</h3>
<p>W = mg (g ≈ 10 N/kg). Weight acts at the centre of mass; mass is invariant. Density ρ = m/V.</p>

<h3>4. Newton''s laws and resultant force</h3>
<ul>
<li>Resultant: colinear addition/subtraction; perpendicular by Pythagoras.</li>
<li>F = ma. Terminal velocity: drag grows with speed until it balances weight.</li>
<li>Third law pairs: equal magnitude, opposite direction, different bodies.</li>
</ul>

<h3>5. Momentum (Extended)</h3>
<p>p = mv; impulse Ft = Δ(mv); conservation: Σp<sub>before</sub> = Σp<sub>after</sub> (explosions, collisions).</p>
<p><strong>Example:</strong> 2 kg at 3 m/s hits 1 kg at rest, combined 1 m/s: 6 = 3v ⇒ v = 2 m/s.</p>

<h3>6. Moments and equilibrium</h3>
<ul>
<li>Moment = F × perpendicular distance from pivot.</li>
<li>Principle of moments: Σclockwise = Σanticlockwise.</li>
<li>Equilibrium: resultant force = 0 and resultant moment = 0.</li>
</ul>
<p><strong>Example:</strong> 100 N at 0.3 m balances F at 0.5 m: F = 60 N.</p>', updated_at = now() where id = 'e08e10e6-d123-407a-877f-dcc7c82c3d5b';
update public.study_materials set content = '<h2>Waves &amp; Sound</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> general wave properties; reflection/refraction/diffraction; sound.</p>

<h3>1. Wave basics</h3>
<p>v = fλ. Transverse (oscillation ⊥ travel — light, water, S-waves) vs longitudinal (parallel — sound, P-waves). Amplitude, wavelength, frequency f = 1/T; wavefront diagrams.</p>

<h3>2. Ripple tank behaviours</h3>
<ul>
<li><strong>Reflection</strong>: angle in = angle out; speed/frequency unchanged, direction changes.</li>
<li><strong>Refraction</strong>: speed change at boundary bends wavefronts (shallow water slows ripples).</li>
<li><strong>Diffraction</strong>: spreading through gaps ≈ λ wide; around edges.</li>
</ul>

<h3>3. Electromagnetic spectrum (order)</h3>
<p>Radio → micro → IR → visible (red 700 nm – violet 400 nm) → UV → X → gamma. All travel at 3 × 10⁸ m/s in vacuum; transverse; uses and dangers (IR heating; UV skin; X/gamma ionising).</p>

<h3>4. Sound</h3>
<ul>
<li>Longitudinal; needs a medium (bell in vacuum demo). Speed ~340 m/s air, faster in liquids/solids.</li>
<li>Range 20 Hz–20 kHz; ultrasound &gt; 20 kHz (sonar, prenatal scans, cleaning).</li>
<li>Pitch ↔ frequency; loudness ↔ amplitude.</li>
</ul>

<h3>5. Echo problems</h3>
<p>Distance = (v × t)/2 (there and back).</p>
<p><strong>Example:</strong> echo after 0.6 s, v = 340 → cliff 102 m away.</p>

<p><strong>Exam tips:</strong> in diagrams always label wavelength as crest-to-crest; for refraction, state "changes speed" first, then direction; quote EM uses with the hazard.</p>', updated_at = now() where id = '4c3feece-d824-42a8-88ae-a9f3c5c313f7';
update public.study_materials set content = '<h2>Pressure &amp; Density</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> pressure &amp; pressure differences in fluids, density review (Extended pressure-depth).</p>

<h3>1. Pressure basics</h3>
<p>p = F/A (Pa = N/m²). Increase F or decrease A to raise pressure; explain applications (snowshoes, knives, hydraulic press).</p>

<h3>2. Liquids</h3>
<ul>
<li>Pressure increases with depth: p = ρgh (Extended).</li>
<li>Same level, same liquid ⇒ same pressure (hydrostatic paradox).</li>
<li>Hydraulic systems transmit pressure — force multiplier: F₁/A₁ = F₂/A₂.</li>
</ul>

<h3>3. Atmospheric pressure</h3>
<p>~10⁵ Pa at sea level; demonstrated by collapsing can, mercury barometer 760 mmHg; decreases with altitude.</p>

<h3>4. Density revisited</h3>
<p>ρ = m/V; floating condition; upthrust = weight of displaced fluid (qualitative).</p>

<h3>5. Gas pressure (particle model)</h3>
<p>Particles collide with walls → force per area. Volume ↓ at same T ⇒ pressure ↑ (more frequent collisions). Temperature ↑ ⇒ faster particles ⇒ more frequent, harder impacts.</p>', updated_at = now() where id = '61da5c21-d745-4a51-ba0c-2a861af41061';
update public.study_materials set content = '<h2>Thermal Physics</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> kinetic particle model; thermal expansion; specific heat capacity; melting/boiling; conduction, convection, radiation.</p>

<h3>1. Kinetic model</h3>
<p>Solid: fixed positions, vibrate — fixed shape/volume. Liquid: move around, touching — fixed volume, flows. Gas: far apart, fast random motion — fills container. Brownian motion evidences random molecular motion.</p>

<h3>2. Gas pressure and temperature</h3>
<p>Pressure from wall collisions. Heating at fixed volume → faster particles → more frequent, harder collisions → higher pressure.</p>

<h3>3. Thermal expansion</h3>
<p>Heating → particles vibrate more → solids expand slightly (gases expand most). Applications: bimetallic strip (fire alarm/thermostat), gaps in bridges/rails; the liquid-in-glass thermometer.</p>

<h3>4. Specific heat capacity</h3>
<p>c = ΔE/(mΔθ). Heating: ΔE = mcΔθ.</p>
<p><strong>Example:</strong> 2 kg water (c = 4200), 20→80 °C: ΔE = 2×4200×60 = 504 kJ.</p>
<p>High c of water → coolant; temperature rise measured with known heater power P in time t: c = Pt/(mΔθ).</p>

<h3>5. State changes</h3>
<p>Melting/boiling at fixed temperature despite heating (energy breaks bonds, not temperature). Condensation/ freezing release energy. Impurities raise melting point of mixtures/lower freezing; boiling needs nucleation.</p>

<h3>6. Transfer: conduction, convection, radiation</h3>
<ul>
<li><strong>Conduction</strong>: mainly metals (delocalised electrons + lattice vibration); non-metals poor; insulators trap air.</li>
<li><strong>Convection</strong>: hot fluid expands, density falls, rises; denser cool fluid sinks — currents.</li>
<li><strong>Radiation</strong>: infrared EM waves; no medium; matte black best absorber/emitter, shiny silver worst.</li>
</ul>
<p>Applications: vacuum flask, house insulation, car radiators, solar heating panels.</p>', updated_at = now() where id = '944cae75-d042-4e44-adb7-84ee5a7e4f18';
update public.study_materials set content = '<h2>Measurement &amp; Units</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> 1.1 lengths &amp; volumes; 1.2 density; 1.3 forces &amp; motion context (measurements) — plus measurement techniques, SI units, scalars/vectors.</p>

<h3>1. Measuring</h3>
<ul>
<li>Length: ruler (mm), vernier calipers (0.1 mm / 0.01 cm), micrometer screw gauge (0.01 mm).</li>
<li>Volume: measuring cylinder read at the meniscus bottom; regular solids by calculation; irregular by displacement (eureka can).</li>
<li>Time: stopwatch — human reaction time ±0.2 s; measure many oscillations and divide (e.g. 20 T).</li>
<li>Pendulum: T = time/oscillations; f = 1/T.</li>
</ul>

<h3>2. SI units and prefixes</h3>
<table border="1" cellpadding="6"><tr><th>Quantity</th><th>Unit</th><th>Symbol</th></tr>
<tr><td>length</td><td>metre</td><td>m</td></tr>
<tr><td>mass</td><td>kilogram</td><td>kg</td></tr>
<tr><td>time</td><td>second</td><td>s</td></tr>
<tr><td>current</td><td>ampere</td><td>A</td></tr>
<tr><td>temperature</td><td>kelvin (°C used)</td><td>K</td></tr></table>
<p>kilo 10³; centi 10⁻²; milli 10⁻³; micro 10⁻⁶; nano 10⁻⁹.</p>

<h3>3. Scalars and vectors</h3>
<p>Scalars: distance, speed, mass, energy, time. Vectors: displacement, velocity, acceleration, force, weight, momentum. Vector addition by scale diagram (tip-to-tail) or by components.</p>

<h3>4. Density</h3>
<p>ρ = m/V (kg/m³ or g/cm³; 1 g/cm³ = 1000 kg/m³). Determining: mass on balance; volume by displacement. Floating: ρ<sub>object</sub> &lt; ρ<sub>fluid</sub>.</p>

<h3>5. Accuracy and improvements</h3>
<p>Avoid parallax (eye level with reading), zero errors (subtract the zero reading), measure multiple laps for small times. Suggest improvements by naming the error and the fix.</p>', updated_at = now() where id = '944a7eb4-3cc4-4439-bc06-3250049bf117';
update public.study_materials set content = '<h2>Data Representation</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> binary/hex, two''s complement, BCD, text/image/sound encoding, file sizes, compression.</p>

<h3>1. Number systems</h3>
<ul>
<li>Binary place values 128…1; hex digits 0–9, A–F; one hex digit = one nibble (4 bits).</li>
<li>Conversions: binary ↔ decimal ↔ hex. 0101 1010 → 5A; FF = 255.</li>
<li><strong>BCD</strong>: 4 bits per decimal digit — 0029 → 0000 0000 0010 1001. Used in clocks/calculators; easier digit conversions, more bits than pure binary.</li>
</ul>

<h3>2. Two''s complement (signed)</h3>
<p>MSB is negative: −128 64 32 16 8 4 2 1. −5 = 1111 1011. Range 8-bit: −128…+127.</p>
<p>Negating: invert bits, add 1. Subtraction: add the negated number — 7 − 5 = 7 + (−5) = 0000 0111 + 1111 1011 = 0000 0010.</p>

<h3>3. Text</h3>
<p>ASCII 7-bit (128 chars) → extended sets; Unicode for all scripts (UTF-8 variable width). Character sets map codes to glyphs; uppercase/lowercase codes differ by one bit.</p>

<h3>4. Images and sound</h3>
<ul>
<li>Bitmap: pixels; colour depth = bits per pixel. File size (bits) = W × H × depth. Metadata (width, height, depth) stores dimensions.</li>
<li>Sound: sample rate (Hz), resolution (bits per sample), track duration × channels. Higher rate/depth = better fidelity, larger files.</li>
</ul>

<h3>5. Compression</h3>
<ul>
<li><strong>Lossless</strong> (RLE, ZIP): exact restore — text/code must use it. RLE example: AAABBBCC → 3A3B2C; effective with runs.</li>
<li><strong>Lossy</strong> (JPEG, MP3): discards perceptually minor data — photos/music OK, text never.</li>
</ul>

<p><strong>Exam tips:</strong> show full working in conversions; for size questions write the formula first with units; state the <em>reason</em> a compression type suits the file.</p>', updated_at = now() where id = '3dd6d5c0-35ea-44c6-8f24-ad74aad0d101';
update public.study_materials set content = '<h2>Nuclear Physics</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> nuclear model, radioactivity, decay types, half-life, safety, fission/fusion (Extended).</p>

<h3>1. The nuclear model</h3>
<p>Nucleus (protons +, neutrons 0) with orbiting electrons (−). Nuclide notation ᴬ_Z X. Isotopes: same Z, different A. Rutherford scattering established the nuclear model; proton number Z, nucleon number A.</p>

<h3>2. Radiation types</h3>
<table border="1" cellpadding="6"><tr><th>Type</th><th>Nature</th><th>Range (air)</th><th>Stopped by</th></tr>
<tr><td>alpha α</td><td>helium nucleus (2p2n)</td><td>few cm</td><td>paper</td></tr>
<tr><td>beta β⁻</td><td>fast electron</td><td>~20–30 cm</td><td>few mm aluminium</td></tr>
<tr><td>gamma γ</td><td>EM wave</td><td>very far</td><td>thick lead/concrete</td></tr></table>
<p>Deflection in fields: α/β opposite, γ none. Ionising: α &gt; β &gt; γ. Background radiation: radon, cosmic, rocks, medical, fallout.</p>

<h3>3. Decay equations</h3>
<ul>
<li>α: A −4, Z −2 (e.g. ²³⁸₉₂U → ²³⁴₉₀Th + α).</li>
<li>β⁻: neutron → proton; A same, Z +1 (e.g. ¹⁴₆C → ¹⁴₇N + β⁻).</li>
<li>γ: no change to A or Z.</li>
</ul>
<p>Balance A and Z on both sides — that is the check.</p>

<h3>4. Half-life</h3>
<p>Time for half the unstable nuclei to decay (random process). Read from a decay curve or count halves: 80 → 40 → 20 over two half-lives.</p>
<p><strong>Example:</strong> 800 Bq, half-life 2 h → 200 Bq after 4 h.</p>

<h3>5. Safety and uses</h3>
<p>Uses: medical tracers (β/γ), sterilisation, thickness gauge (β), dating (C-14), smoke alarms (α). Safety: distance, time, shielding, wear badges, store in lead. Handle with tongs; never point at people.</p>

<h3>6. Fission and fusion (Extended)</h3>
<p>Fission: heavy nucleus splits (U-235 + neutron), chain reaction controlled by moderators/control rods — power stations. Fusion: light nuclei join (stellar) — needs huge T/P; releases more energy per kg; no long-lived waste.</p>', updated_at = now() where id = 'd7f2e9e8-ff4a-4fba-9960-48d8ca800dd6';
update public.study_materials set content = '<h2>Networking &amp; Communication</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> transmission modes, serial/parallel, packet switching, protocols, LAN/WAN, hardware, security layers.</p>

<h3>1. Transmission basics</h3>
<ul>
<li>Serial: one bit at a time — reliable over distance, cheaper cable.</li>
<li>Parallel: several bits at once — faster over short runs; skew/crosstalk limit distance.</li>
<li>Simplex / half-duplex / full-duplex direction; bandwidth (bits/s) vs bit rate.</li>
</ul>

<h3>2. Packets</h3>
<p>Header (sender/receiver addresses, sequence number) + payload + trailer (checksum). Packet switching: routes vary, packets reassembled at destination; checksum failure → re-request. Benefits: robustness, shared lines; delays/reassembly overhead.</p>

<h3>3. Protocols</h3>
<p>TCP/IP stack layers (application, transport, network, link). HTTP/HTTPS (TLS encryption), FTP (with login + commands), email: SMTP send, POP3/IMAP retrieve. Bluetooth/Wi-Fi for WPAN/WLAN.</p>

<h3>4. Network types &amp; hardware</h3>
<p>LAN (site) vs WAN (internet). Router (joins networks, IP), switch (MAC frames within LAN), gateway (protocol translation), NIC, WAP. MAC address (burned-in, layer 2) vs IP address (assigned, layer 3).</p>

<h3>5. Security in transmission</h3>
<p>Encryption scrambles plaintext → ciphertext (key needed); HTTPS = HTTP over TLS; firewall packet filtering by port/IP; authentication (user+pass, 2FA); access levels.</p>

<p><strong>Exam tips:</strong> explain <em>why</em> skew limits parallel over distance; compare MAC vs IP in a table; protocol questions want "rules for communication", not acronyms alone.</p>', updated_at = now() where id = '11594218-4521-43d6-bccd-fb79cda469b4';
update public.study_materials set content = '<h2>Operating Systems</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> OS roles, memory/process management, hardware–software layer, interrupts, buffers, utility software.</p>

<h3>1. What an OS does</h3>
<p>Manages memory, processes/files, I/O via drivers, security (users, permissions), and provides the UI (CLI/GUI) between user, applications and hardware.</p>

<h3>2. Memory and process management</h3>
<ul>
<li>Paging/segmentation move programs in/out; virtual memory extends RAM to disk when RAM is full.</li>
<li>Multitasking: scheduler gives each process time slices; context switching saves/restores state.</li>
</ul>

<h3>3. Interrupts and buffers</h3>
<p>Interrupts signal events (I/O complete, timer); CPU saves context, services via ISR, resumes. Buffers hold data in transit (printing) so slow devices don''t block the CPU; spooling queues jobs.</p>

<h3>4. Utility software</h3>
<p>Disk formatter, defragmenter (reduces head movement on HDDs; unnecessary for SSD), backup scheduler, compression, antivirus, file compression.</p>

<h3>5. UI and drivers</h3>
<p>CLI: precise, scriptable, low overhead. GUI: icons/windows, discoverable, more resources. Device drivers translate OS calls to hardware specifics — each device needs its own.</p>

<p><strong>Exam tips:</strong> "manage" verbs earn marks: manages memory, manages processes, manages peripherals; explain virtual memory by RAM-full scenario, not definition alone.</p>', updated_at = now() where id = '77c32ddd-d720-4973-9b42-3e1600709841';
update public.study_materials set content = '<h2>Programming Concepts</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> variables/constants, data types, selection/iteration, arrays, file handling, subroutines, scope, IDE tools.</p>

<h3>1. Basics</h3>
<p>Constants vs variables; types: INTEGER, REAL, CHAR, STRING, BOOLEAN, DATE; casting between them. Declaration with meaningful names.</p>

<h3>2. Selection and iteration</h3>
<pre>IF score >= 50 THEN
  grade ← "pass"
ELSE
  grade ← "fail"
ENDIF

CASE OF grade
  "A" : OUTPUT "excellent"
  OTHERWISE : OUTPUT "keep going"
ENDCASE

REPEAT
  INPUT pin
UNTIL pin = storedPin

FOR i ← 1 TO 10 STEP 2 ... NEXT i</pre>
<p>WHILE: condition first (may not run); REPEAT: runs at least once.</p>

<h3>3. Arrays</h3>
<p>Fixed size, indexed (0- or 1-based per spec); 2D arrays: row, column. Bounds errors when index leaves range. Traversal with FOR loops.</p>

<h3>4. Files</h3>
<pre>OPENFILE "data.txt" FOR READ
READFILE "data.txt", line
CLOSEFILE "data.txt"

OPENFILE "log.txt" FOR APPEND
WRITEFILE "log.txt", record</pre>
<p>Modes: READ, WRITE (overwrites), APPEND (adds).</p>

<h3>5. Subroutines</h3>
<p>Procedure (no return) vs function (returns value). Parameters by value (copy) vs reference (original). Local scope inside; global shared — declare deliberately, avoid overuse.</p>

<h3>6. IDE tools</h3>
<p>Syntax highlighting, autocompletion, breakpoints, single stepping, variable watch — name the tool <em>and</em> its debugging benefit.</p>

<p><strong>Exam tips:</strong> use the exam pseudocode style exactly; for 2D arrays, loop rows outer/columns inner; choose WHILE vs REPEAT by "must it run once?"</p>', updated_at = now() where id = 'f2259878-433e-406d-9dea-7531aff6d69a';
update public.study_materials set content = '<h2>Web Technologies</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> HTML structure/tags, CSS styling, JS interactivity, the DOM, microprocessors/controllers in web context.</p>

<h3>1. HTML</h3>
<pre>&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;&lt;title&gt;Page&lt;/title&gt;&lt;/head&gt;
&lt;body&gt;
  &lt;h1&gt;Heading&lt;/h1&gt;
  &lt;p&gt;Paragraph with &lt;strong&gt;bold&lt;/strong&gt; text&lt;/p&gt;
  &lt;img src="pic.jpg" alt="description"&gt;
  &lt;a href="https://example.com"&gt;Link&lt;/a&gt;
  &lt;table&gt;&lt;tr&gt;&lt;td&gt;cell&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;
&lt;/body&gt;
&lt;/html&gt;</pre>
<p>Head holds metadata/title; body holds visible content; hypertext links via &lt;a href&gt;.</p>

<h3>2. CSS</h3>
<pre>p { color: red; font-size: 14px; }
.highlight { background-color: yellow; }
#header { text-align: center; }</pre>
<p>Element, class (.) and id (#) selectors; inline vs external stylesheets; separation of content (HTML) from presentation (CSS).</p>

<h3>3. JavaScript and the DOM</h3>
<pre>document.getElementById("demo").innerHTML = "Hello";
document.getElementsByClassName("item")[0].style.color = "blue";</pre>
<p>DOM = the browser''s object model of the page; JS reads/changes it for interactivity (validation, sliders, dynamic text). Events (click, submit) trigger functions.</p>

<h3>4. How pages load</h3>
<p>URL → DNS lookup → server request → HTML parsed → assets fetched → DOM built → render. Layers: structure (HTML) → presentation (CSS) → behaviour (JS).</p>

<p><strong>Exam tips:</strong> write tags with correct closing pairs; explain DOM operations as "find element by id … then change property"; separate structure/presentation/behaviour in answers.</p>', updated_at = now() where id = '37c076d2-e903-4a57-8672-96dd9b97fbec';
update public.study_materials set content = '<h2>Robotics &amp; AI</h2>
<p><strong>Cambridge IGCSE 0478 (2026–2028):</strong> AI characteristics, machine learning basics, robotics/simulation contexts, automated systems.</p>

<h3>1. AI characteristics</h3>
<p>Systems exhibiting: planning, learning, reasoning, problem-solving, perception, knowledge representation. Narrow (task-specific) vs general AI distinction for discussion answers.</p>

<h3>2. Machine learning</h3>
<p>Supervised (labelled data — spam filters), unsupervised (clusters — segmentation), reinforcement (rewards — game agents). Training/evaluation loop: train on a set, test on unseen data; overfitting = memorising rather than generalising.</p>

<h3>3. Robotics</h3>
<p>Components: sensors (input), processors (decision), actuators/motors (output), power. Examples: manufacturing arms, delivery drones, autonomous vehicles (LIDAR + vision). Benefits: precision, 24/7 operation, dangerous jobs; concerns: job displacement, safety, cost.</p>

<h3>4. Automated systems &amp; simulation</h3>
<p>Sensors → processor → actuators loops (greenhouses, traffic lights, self-checkouts). Simulation models real systems cheaply and safely (flight training, weather, crash tests) — limitations: model quality, missing variables.</p>

<h3>5. Ethics of AI</h3>
<p>Bias from unrepresentative training data; opacity of decisions; accountability for errors; privacy of training data; effect on employment.</p>

<p><strong>Exam tips:</strong> for "describe how AI could be used in X" — tie each AI characteristic to a concrete step in the scenario; for evaluations, give both sides then a justified conclusion.</p>', updated_at = now() where id = 'f4ec1c0b-4462-46b9-98fe-457d9fbd7e90';
update public.study_materials set content = '<h2>Energy, Work &amp; Power</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> stores and transfers, KE/PE, work, energy sources, power, efficiency.</p>

<h3>1. Energy stores &amp; transfers</h3>
<p>Stores: kinetic, gravitational, elastic, chemical, nuclear, thermal. Transfer mechanisms: mechanically, electrically, heating, waves. Energy is conserved overall; transfers via <strong>work</strong> done.</p>

<h3>2. Formulas</h3>
<ul>
<li>KE = ½mv²; PE = mgh.</li>
<li>Work W = Fd (force along displacement, joules).</li>
<li>Power P = W/t = E/t; P = Fv for constant speed.</li>
</ul>
<p><strong>Example:</strong> 0.5 kg at 4 m/s: KE = 4 J. Lift 2 kg by 3 m: PE = 60 J (g = 10).</p>

<h3>3. Energy sources</h3>
<p>Renewable: solar, wind, hydro, geothermal, biofuel, tidal — replenished. Non-renewable: fossil fuels, nuclear — finite. Discuss reliability, cost, pollution for "evaluate" questions.</p>

<h3>4. Efficiency</h3>
<p>Efficiency = useful output ÷ total input (×100%). Sankey diagrams show losses.</p>
<p><strong>Example:</strong> motor: 150 J useful from 600 J → 25%.</p>

<h3>5. Energy-chain problems</h3>
<p>Equating KE loss to PE gain: v = √(2gh) for frictionless drop; braking distance grows with v².</p>

<p><strong>Exam tips:</strong> define work as "force × distance moved <em>in the direction of the force</em>"; use g = 10 unless told otherwise; efficiency is a ratio — no units.</p>', updated_at = now() where id = 'd371087c-b171-4536-ae7e-16eadfdba067';
update public.study_materials set content = '<h2>Electricity &amp; Circuits</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> simple circuits, current, p.d., resistance, series/parallel, electrical safety, practical electricity.</p>

<h3>1. Circuit symbols &amp; current</h3>
<p>Conventional current: + → − (electron flow opposite). I = Q/t. Ammeter in series; voltmeter in parallel.</p>

<h3>2. Current, p.d., e.m.f.</h3>
<ul>
<li>Current: rate of charge flow; same everywhere in series.</li>
<li>p.d.: energy per coulomb <em>across a component</em>; e.m.f.: electrical energy per coulomb <em>given by the source</em>.</li>
</ul>

<h3>3. Resistance</h3>
<ul>
<li>R = V/I. Ohmic conductor: V ∝ I at constant temperature.</li>
<li>Series: R = R₁ + R₂ + …; same current; p.d. shares in proportion to R.</li>
<li>Parallel: 1/R = 1/R₁ + 1/R₂; same p.d.; current splits (inverse-R share).</li>
<li>Resistance ∝ length, ∝ 1/area (wires).</li>
</ul>

<h3>4. Components</h3>
<p>Fixed/variable resistors, LDR (light ↑ R ↓), thermistor (T ↑ R ↓), diode/LED (one-way), relay, filament lamp (R grows as T rises — V–I curve flattens).</p>

<h3>5. Power and energy</h3>
<p>P = VI = I²R = V²/R; E = VIt. Fuse rating just above normal current; earth wire, double insulation, circuit breakers (trip quickly, resettable).</p>
<p><strong>Example:</strong> 230 V, 2 A heater: P = 460 W; correct fuse 3 A or 5 A.</p>

<h3>6. Digital electronics basics (syllabus 4.5 context)</h3>
<p>Analogue vs digital; logic gates drive outputs from inputs (see CS link); sensors feed comparator-style circuits.</p>

<p><strong>Exam tips:</strong> series: current same; parallel: p.d. same — say which before calculating; always compute total resistance first in mixed circuits.</p>', updated_at = now() where id = 'cad3375c-cc3e-4846-8a72-441509ebada1';
update public.study_materials set content = '<h2>Magnetism &amp; Electromagnetism</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> magnets &amp; fields; magnetic effect of a current; force on a current-carrying conductor; motor effect; electromagnetic induction (Extended); transformers (Extended).</p>

<h3>1. Magnets and fields</h3>
<p>Iron/steel/cobalt/nickel; like poles repel. Field lines exit N, enter S; compass plotting; plotting compass aligns with field. Induced magnetism: iron (temporary) vs steel (permanent).</p>

<h3>2. Electromagnets</h3>
<p>Solenoid field like a bar magnet; strength ↑ with current, turns, iron core. Uses: relays, scrapyard crane, electric bell, speaker. Hard/soft magnetic materials choose permanent vs core use.</p>

<h3>3. Force on a current-carrying conductor</h3>
<p>F = BIL, direction by Fleming''s left hand (fIeld, current, force). Reversing current or field reverses force. D.C. motor: coil, commutator reverses current each half-turn for continuous rotation; speed/torque ↑ with current, field strength, turns/area.</p>

<h3>4. Electromagnetic induction (Extended)</h3>
<p>Induced e.m.f. when a conductor cuts field lines or flux changes. Fleming''s right hand (generator). Factors: speed, field strength, turns. A.C. generator: slip rings; dynamo effect; Lenz''s law opposes change (direction of induced current).</p>

<h3>5. Transformers (Extended)</h3>
<p>V<sub>p</sub>/V<sub>s</sub> = N<sub>p</sub>/N<sub>s</sub>; P<sub>in</sub> ≈ P<sub>out</sub> (100% assumed): I<sub>p</sub>V<sub>p</sub> = I<sub>s</sub>V<sub>s</sub>. Step-up raises V, lowers I → lower I²R transmission losses; a.c. required (changing flux).</p>', updated_at = now() where id = '53568d22-201e-404e-83d9-0e61912f2c1b';
update public.study_materials set content = '<h2>Earth &amp; Space</h2>
<p><strong>Cambridge IGCSE 0625 (2026–2028):</strong> Earth &amp; Solar System; stars &amp; the Universe (Extended).</p>

<h3>1. Earth, Moon, Sun</h3>
<p>Earth rotates 24 h (day/night), orbits 365¼ d (year + leap). Moon orbits Earth ~27.3 d; phases from viewing angle; lunar/solar eclipses when aligned. Seasons from axial tilt (23.5°), not distance.</p>

<h3>2. Solar system</h3>
<p>Planets (Mercury → Neptune), dwarf planets (Pluto), moons, asteroids, comets (eccentric orbits, tails away from Sun), natural satellites. Gravity keeps orbits; orbital speed &amp; radius relate to the central mass.</p>

<h3>3. Orbital motion</h3>
<p>Orbital speed v = 2πr/T. T grows with r (Kepler trend). Comets speed up near the Sun (ellipse, Sun at focus).</p>

<h3>4. Stars (Extended)</h3>
<p>Star formation: nebula → protostar (gravity, KE→thermal) → main sequence (hydrogen fusion: H→He, radiation pressure balances gravity) → red giant → white dwarf (Sun-mass) or supergiant → supernova → neutron star/black hole (massive stars). Elements heavier than iron form in supernovae.</p>

<h3>5. Universe (Extended)</h3>
<p>The Sun is one star in the Milky Way; the Milky Way is one of billions of galaxies. Redshift: receding galaxies show stretched wavelengths → the Universe is expanding → Big Bang model; CMB is the afterglow. Hubble: farther ⇒ faster recession.</p>

<h3>6. Scales</h3>
<p>light-year = distance light travels in a year (9.5 × 10¹⁵ m); astronomical unit = Earth–Sun distance (1.5 × 10¹¹ m).</p>', updated_at = now() where id = '798f9e7d-33c5-456e-9070-c32874b67978';
