const fs = require("fs");
const https = require('https');
const TOKEN = (fs.readFileSync(".freebuff/get-keys.cjs", "utf8").match(/sbp_[a-f0-9]+/) || [])[0];
const PROJECT = 'zzliiazovezhxbmfeqco';

function query(sql) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({ query: sql });
    const options = {
      hostname: 'api.supabase.com',
      path: `/v1/projects/${PROJECT}/database/query`,
      method: 'POST',
      headers: {
        Authorization: `Bearer ${TOKEN}`,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(body)
      }
    };
    const req = https.request(options, res => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        try { resolve(JSON.parse(data)); } catch(e) { resolve(data); }
      });
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

function esc(s) { return JSON.stringify(s); }

const topics = [
  {
    name: 'Data Representation',
    lesson: `# Data Representation\n\n## Number Systems\n\n### Binary (Base 2)\nComputers use binary — only 0s and 1s. Each digit is a **bit**. 8 bits = 1 **byte**.\n\nPlace values: 128, 64, 32, 16, 8, 4, 2, 1\n\n**Example:** 01010110 = 0+64+0+16+0+4+2+0 = 86\n\n### Hexadecimal (Base 16)\nUsed as shorthand for binary. Uses 0-9 and A-F.\n\n| Decimal | Binary | Hex |\n|---------|--------|-----|\n| 0 | 0000 | 0 |\n| 10 | 1010 | A |\n| 15 | 1111 | F |\n| 16 | 0001 0000 | 10 |\n| 255 | 1111 1111 | FF |\n\n**Why hex?** Shorter, easier to read than binary. 1 hex digit = 4 bits.\n\n### Conversions\n- Binary → Decimal: add place values where there's a 1\n- Decimal → Binary: divide by 2, read remainders upwards\n- Binary → Hex: group into 4-bit nibbles, convert each\n- Hex → Binary: convert each digit to 4 bits\n\n## Data Storage\n- **Bit:** 0 or 1\n- **Byte:** 8 bits (can store 0-255)\n- **KB:** 1024 bytes\n- **MB:** 1024 KB\n- **GB:** 1024 MB\n- **TB:** 1024 GB\n\n## Character Encoding\n\n### ASCII\n- 7-bit code (128 characters)\n- A = 65, a = 97, 0 = 48\n- Can only represent English characters\n\n### Unicode\n- Uses more bits to represent ALL world scripts\n- UTF-8: variable width (1-4 bytes per character)\n- Can represent emojis, Chinese, Arabic, etc.\n\n## Images\n- Made of **pixels** (picture elements)\n- **Resolution:** number of pixels (e.g., 1920×1080)\n- **Colour depth:** bits per pixel (1-bit = black/white, 24-bit = 16.7 million colours)\n- **File size = resolution × colour depth**\n- Higher resolution and colour depth = larger file\n\n### Metadata\nData about data: file name, date created, resolution, author, etc.\n\n## Sound\n- Sound waves are analog; computers store digital samples\n- **Sampling:** measuring the amplitude at regular intervals\n- **Sampling rate:** samples per second (CD = 44,100 Hz)\n- **Bit depth:** bits per sample (CD = 16-bit)\n- Higher sampling rate and bit depth = better quality, larger file\n\n## Compression\n\n### Lossless (no data lost)\n- Reduces file size without losing quality\n- Examples: Run Length Encoding, Huffman coding\n- Used for: text, program files\n\n### Lossy (some data lost)\n- Removes data deemed less important\n- Cannot be restored to original\n- Examples: JPEG (images), MP3 (audio)\n- Used for: photos, music, video`,
    questions: [
      { q: 'Convert 01100101 to decimal:', opts: ['101', '97', '100', '99'], correct: 1, explain: '0+64+32+0+0+4+0+1 = 101.' },
      { q: 'What is 255 in hexadecimal?', opts: ['FF', '15', '1111', '16'], correct: 1, explain: '255 = 15×16 + 15 = FF in hex.' },
      { q: '1 byte equals:', opts: ['8 bits', '10 bits', '16 bits', '4 bits'], correct: 1, explain: '1 byte = 8 bits.' },
      { q: 'What is the ASCII value of capital A?', opts: ['65', '97', '48', '66'], correct: 1, explain: 'Capital A = 65 in ASCII. Lowercase a = 97.' },
      { q: 'An image is 800×600 pixels with 24-bit colour. File size (in bits)?', opts: ['11,520,000', '1,440,000', '480,000', '24,000'], correct: 1, explain: '800 × 600 × 24 = 11,520,000 bits.' },
      { q: 'Unicode is needed because ASCII:', opts: ['Can only represent 128 characters', 'Is too slow', 'Uses too much memory', 'Cannot store numbers'], correct: 1, explain: 'ASCII covers only English characters; Unicode covers all world scripts.' },
      { q: 'Which compression method loses some data?', opts: ['Lossy', 'Lossless', 'Run Length Encoding', 'Huffman coding'], correct: 1, explain: 'Lossy compression removes data (e.g., JPEG, MP3).' },
      { q: 'What does 1024 KB equal?', opts: ['1 MB', '1 GB', '1 TB', '1 byte'], correct: 1, explain: '1024 KB = 1 MB.' },
      { q: 'Convert hex 1A to decimal:', opts: ['26', '110', '27', '16'], correct: 1, explain: '1×16 + 10 = 26.' },
      { q: 'CD audio sampling rate is:', opts: ['44,100 Hz', '22,050 Hz', '8,000 Hz', '48,000 Hz'], correct: 1, explain: 'Standard CD sampling rate = 44,100 Hz.' }
    ]
  },
  {
    name: 'Algorithms & Programming',
    lesson: `# Algorithms & Programming\n\n## What is an Algorithm?\nA step-by-step set of instructions to solve a problem.\n\n## Flowcharts\nStandard symbols:\n- **Oval:** Start/End\n- **Rectangle:** Process/Calculation\n- **Diamond:** Decision (Yes/No)\n- **Parallelogram:** Input/Output\n- **Arrow:** Flow direction\n\n## Pseudocode\nWritten like code but in plain English:\n\`\`\`\nIF mark >= 50 THEN\n  PRINT "Pass"\nELSE\n  PRINT "Fail"\nENDIF\n\`\`\`\n\n## Trace Tables\nTrack the value of variables step by step through an algorithm.\n\n## Three Basic Structures\n1. **Sequence:** Instructions run one after another\n2. **Selection:** IF...THEN...ELSE (choice)\n3. **Iteration (Loop):** Repeat while/until a condition is met\n\n## Types of Iteration\n- **WHILE loop:** Tests condition BEFORE each iteration\n- **REPEAT...UNTIL loop:** Tests condition AFTER each iteration (runs at least once)\n- **FOR loop:** Runs a specific number of times\n\n## Searching\n- **Linear search:** Check each item one by one (O(n))\n- **Binary search:** Divide and conquer on SORTED data (O(log n))\n\n## Sorting\n- **Bubble sort:** Compare adjacent pairs, swap if wrong order\n- **Insertion sort:** Insert each item into correct position\n- **Merge sort:** Divide list in half, sort each half, merge\n\n## Variables and Constants\n- **Variable:** Named storage whose value can change\n- **Constant:** Named storage whose value cannot change\n\n## Data Types\n- **Integer:** whole number\n- **Real/Float:** decimal number\n- **String:** text\n- **Boolean:** True/False\n- **Character:** single letter/symbol\n\n## Operators\n- **Arithmetic:** +, -, *, /, MOD, DIV\n- **Comparison:** =, <>, <, >, <=, >=\n- **Logical:** AND, OR, NOT\n\n## Procedures and Functions\n- **Procedure:** block of code that performs a task (no return value)\n- **Function:** block of code that returns a value\n\n## String Operations\n- CONCATENATE (join), LENGTH, SUBSTRING, FIND/SEARCH, UPPER, LOWER\n\n## Array/List Operations\n- Declare, access by index (starting from 0 or 1), loop through elements`,
    questions: [
      { q: 'In a flowchart, a diamond shape represents:', opts: ['A decision', 'A process', 'Input/Output', 'Start/End'], correct: 1, explain: 'Diamonds are used for YES/NO decisions.' },
      { q: 'Which loop type tests the condition AFTER executing?', opts: ['REPEAT...UNTIL', 'WHILE', 'FOR', 'IF'], correct: 1, explain: 'REPEAT...UNTIL runs at least once before testing.' },
      { q: 'Binary search requires data to be:', opts: ['Sorted', 'Random', 'In a stack', 'In a queue'], correct: 1, explain: 'Binary search only works on sorted data.' },
      { q: 'What does MOD return for 17 MOD 5?', opts: ['2', '3', '4', '17'], correct: 1, explain: '17 ÷ 5 = 3 remainder 2. MOD returns the remainder.' },
      { q: 'A constant is:', opts: ['A value that cannot change', 'A variable with a fixed name', 'A type of loop', 'An output device'], correct: 1, explain: 'A constant\'s value is set once and cannot be modified.' },
      { q: 'Which is NOT a valid data type?', opts: ['Array', 'Integer', 'String', 'Boolean'], correct: 1, explain: 'Array is a data structure, not a primitive data type.' },
      { q: 'Bubble sort compares:', opts: ['Adjacent pairs of elements', 'First and last elements', 'Random pairs', 'All elements at once'], correct: 1, explain: 'Bubble sort swaps adjacent elements if they are in wrong order.' },
      { q: 'A function differs from a procedure because it:', opts: ['Returns a value', 'Uses variables', 'Has loops', 'Is faster'], correct: 1, explain: 'A function returns a value; a procedure just performs a task.' },
      { q: 'Pseudocode "REPEAT UNTIL done = TRUE" will:', opts: ['Run at least once', 'Run zero times if done=TRUE', 'Never run', 'Only run when done=TRUE'], correct: 1, explain: 'REPEAT...UNTIL always runs at least once before checking.' },
      { q: 'The string operation CONCATENATE:', opts: ['Joins two strings together', 'Counts characters', 'Extracts part of a string', 'Converts to uppercase'], correct: 1, explain: 'CONCATENATE joins strings: "Hello" + "World" = "HelloWorld".' }
    ]
  },
  {
    name: 'Hardware & Architecture',
    lesson: `# Hardware & Architecture\n\n## Von Neumann Architecture\nThe basic design of most modern computers:\n1. **CPU** processes data\n2. **Memory** stores instructions and data\n3. **Input/Output** devices communicate with outside world\n4. **Buses** carry data between components\n\n## The CPU (Central Processing Unit)\n\n### Components\n- **ALU (Arithmetic Logic Unit):** performs calculations and logical comparisons\n- **Control Unit (CU):** directs operations, fetches instructions from memory\n- **Registers:** tiny, extremely fast storage inside the CPU\n  - **PC (Program Counter):** address of next instruction\n  - **MAR (Memory Address Register):** address of data in memory\n  - **MDR (Memory Data Register):** data being transferred\n  - **ACC (Accumulator):** stores results of calculations\n\n### The Fetch-Execute Cycle\n1. **Fetch:** PC → MAR. Instruction at that address goes to MDR.\n2. **Decode:** CU interprets the instruction.\n3. **Execute:** ALU performs the operation.\n4. **Store:** Result written back to memory or register.\n\n## Memory\n\n| Type | Description | Volatile? |\n|------|-------------|----------|\n| RAM | Random Access Memory — stores current programs and data | Yes |\n| ROM | Read-Only Memory — stores firmware/startup instructions | No |\n| Cache | Small, fast memory near CPU for frequently used data | Yes |\n\n- **Virtual memory:** uses hard disk space as temporary RAM when RAM is full\n- **Cache:** faster than RAM but smaller and more expensive\n\n## Storage\n\n| Type | Examples | Access | Durability |\n|------|----------|--------|------------|\n| Magnetic | Hard disk, floppy | Slow (mechanical) | Good |\n| Optical | CD, DVD, Blu-ray | Medium | Good |\n| Solid-state | SSD, USB stick, SD card | Fast (no moving parts) | Very good |\n\n## Input/Output Devices\n\n| Input | Output |\n|-------|--------|\n| Keyboard | Monitor |\n| Mouse | Printer |\n| Microphone | Speakers |\n| Scanner | Headphones |\n| Webcam | Projector |\n| Touchscreen | Haptic feedback |\n\n## Buses\nThree types of buses connect components:\n1. **Data bus:** carries actual data (bidirectional)\n2. **Address bus:** carries memory addresses (unidirectional)\n3. **Control bus:** carries control signals (e.g., read/write)\n\nWider bus = more data at once = faster\n\n## Factors Affecting CPU Performance\n1. **Clock speed:** cycles per second (GHz) — faster = more instructions per second\n2. **Number of cores:** multi-core CPUs can process multiple tasks simultaneously\n3. **Cache size:** more cache = fewer slow memory accesses\n4. **Word size:** number of bits processed in one cycle (32-bit vs 64-bit)`,
    questions: [
      { q: 'The CPU component that performs calculations is the:', opts: ['ALU', 'Control Unit', 'MAR', 'Cache'], correct: 1, explain: 'The ALU (Arithmetic Logic Unit) does all arithmetic and logic operations.' },
      { q: 'RAM is:', opts: ['Volatile', 'Non-volatile', 'Permanent', 'Slow'], correct: 1, explain: 'RAM loses its contents when power is off (volatile).' },
      { q: 'In the fetch-execute cycle, the PC holds:', opts: ['Address of next instruction', 'The current instruction', 'Data from memory', 'The result'], correct: 1, explain: 'PC (Program Counter) always points to the next instruction to fetch.' },
      { q: 'Which memory is fastest?', opts: ['Cache', 'RAM', 'Hard disk', 'Virtual memory'], correct: 1, explain: 'Cache is the fastest — it\'s built into or right next to the CPU.' },
      { q: 'An SSD is a type of:', opts: ['Solid-state storage', 'Magnetic storage', 'Optical storage', 'RAM'], correct: 1, explain: 'SSD = Solid State Drive — uses flash memory, no moving parts.' },
      { q: 'The address bus is:', opts: ['Unidirectional', 'Bidirectional', 'Wireless', 'Optical'], correct: 1, explain: 'Address bus only sends addresses FROM the CPU TO memory (one direction).' },
      { q: 'Virtual memory uses:', opts: ['Hard disk as temporary RAM', 'Extra RAM modules', 'Cache memory', 'ROM space'], correct: 1, explain: 'When RAM is full, the OS uses disk space as virtual RAM.' },
      { q: 'What does the MAR hold?', opts: ['Memory address of data', 'The data itself', 'The next instruction', 'Calculation results'], correct: 1, explain: 'MAR (Memory Address Register) holds the address being accessed.' },
      { q: 'Which is NOT a factor affecting CPU performance?', opts: ['Monitor resolution', 'Clock speed', 'Number of cores', 'Cache size'], correct: 1, explain: 'Monitor resolution doesn\'t affect CPU speed — it\'s an output concern.' },
      { q: 'The control bus carries:', opts: ['Control signals (read/write)', 'Data', 'Memory addresses', 'Power'], correct: 1, explain: 'Control bus carries signals like read, write, interrupt, clock.' }
    ]
  },
  {
    name: 'Networking & Communication',
    lesson: `# Networking & Communication\n\n## What is a Network?\nTwo or more connected computers that share resources and data.\n\n## Network Types\n| Type | Range | Example |\n|------|-------|---------|\n| PAN | ~10 m | Bluetooth headphones |\n| LAN | Building/Campus | School network |\n| WAN | Country/World | The Internet |\n\n## Star vs Bus Topology\n\n### Star (most common)\nAll devices connect to a central hub/switch\n- ✓ If one cable breaks, only that device is affected\n- ✓ Easy to add/remove devices\n- ✗ If the hub fails, entire network fails\n\n### Bus\nAll devices share a single cable\n- ✓ Cheap and easy to install\n- ✗ If the main cable breaks, entire network fails\n- ✗ Hard to troubleshoot\n\n## Client-Server vs Peer-to-Peer\n\n### Client-Server\n- Central server manages resources and security\n- Clients request services from the server\n- Used in: businesses, schools, websites\n\n### Peer-to-Peer (P2P)\n- All computers are equal — no central server\n- Each computer can share and access files\n- Used in: small home networks, file sharing (BitTorrent)\n\n## The Internet\n- A global WAN connecting millions of networks\n- Uses TCP/IP protocol suite\n\n### How the Internet Works\n1. You type a URL in a browser\n2. **DNS** translates the domain name to an IP address\n3. Your request is sent via routers across the internet\n4. The web server receives the request and sends back the page\n5. Your browser renders the HTML\n\n## Protocols\n\n| Protocol | Purpose |\n|----------|---------|\n| HTTP/HTTPS | Web pages (HTTPS = encrypted) |\n| FTP | File transfer |\n| SMTP | Sending email |\n| POP3/IMAP | Receiving email |\n| TCP/IP | Reliable data transmission |\n| Wi-Fi (802.11) | Wireless LAN |\n\n## Network Security\n\n### Threats\n- **Malware:** viruses, worms, trojans, ransomware\n- **Phishing:** fake emails/sites to steal information\n- **Social engineering:** tricking people into revealing info\n- **Brute force:** trying all possible passwords\n\n### Protection\n- **Firewall:** monitors and controls incoming/outgoing traffic\n- **Encryption:** scramble data so only authorized people can read it\n- **Passwords:** strong, unique passwords\n- **Antivirus:** detects and removes malware\n- **Two-factor authentication:** password + another verification\n- **Access controls:** permissions for who can access what`,
    questions: [
      { q: 'A PAN typically has a range of:', opts: ['~10 m', '~100 m', '~1 km', 'Unlimited'], correct: 1, explain: 'PAN (Personal Area Network) covers ~10 m — Bluetooth range.' },
      { q: 'In a star topology, all devices connect to:', opts: ['A central hub/switch', 'Each other directly', 'A single cable', 'The internet'], correct: 1, explain: 'Star topology: all devices connect to a central point.' },
      { q: 'DNS translates:', opts: ['Domain names to IP addresses', 'IP addresses to MAC addresses', 'Binary to hex', 'HTTP to FTP'], correct: 1, explain: 'DNS (Domain Name System) maps domain names → IP addresses.' },
      { q: 'HTTPS differs from HTTP because it:', opts: ['Is encrypted', 'Is faster', 'Uses different ports', 'Doesn\'t need a browser'], correct: 1, explain: 'HTTPS adds SSL/TLS encryption for secure communication.' },
      { q: 'SMTP is used for:', opts: ['Sending email', 'Receiving email', 'Web browsing', 'File transfer'], correct: 1, explain: 'SMTP = Simple Mail Transfer Protocol — sends email.' },
      { q: 'Which is NOT a network topology?', opts: ['Circular', 'Star', 'Bus', 'Mesh'], correct: 1, explain: 'Star, bus, and mesh are standard topologies. Circular is not.' },
      { q: 'A phishing attack involves:', opts: ['Fake emails/websites to steal info', 'Physically breaking into a building', 'Overloading a server', 'Installing antivirus'], correct: 1, explain: 'Phishing = social engineering via fake communications.' },
      { q: 'What does a firewall do?', opts: ['Monitors and controls network traffic', 'Makes the network faster', 'Stores backup data', 'Cools the CPU'], correct: 1, explain: 'Firewall acts as a barrier, blocking unauthorized traffic.' },
      { q: 'TCP/IP is:', opts: ['A suite of communication protocols', 'A type of malware', 'A programming language', 'An operating system'], correct: 1, explain: 'TCP/IP = Transmission Control Protocol/Internet Protocol — foundation of internet communication.' },
      { q: 'Peer-to-peer vs client-server: P2P has:', opts: ['No central server', 'A central server', 'Better security', 'Faster speeds'], correct: 1, explain: 'P2P: all computers are equal, no central server managing resources.' }
    ]
  },
  {
    name: 'Operating Systems',
    lesson: `# Operating Systems\n\n## What is an Operating System?\nThe OS is system software that manages hardware and software resources. It acts as an interface between the user and the computer.\n\n## Functions of an OS\n\n### 1. Memory Management\n- Allocates RAM to programs\n- Moves data between RAM and virtual memory\n- Prevents programs from accessing each other's memory\n\n### 2. Processor Management (Scheduling)\n- Decides which program gets CPU time\n- Uses time-sharing (multitasking)\n- Prioritizes tasks\n\n### 3. File Management\n- Organizes files in folders/directories\n- Controls access permissions\n- Keeps track of file locations on disk\n\n### 4. Device Management\n- Communicates with hardware via device drivers\n- Manages input/output devices\n- Handles interrupts from devices\n\n### 5. Security\n- User authentication (login/password)\n- Access control (permissions)\n- Protection against unauthorized access\n\n## Utility Programs\n- **Disk defragmenter:** reorganizes fragmented files for faster access\n- **Antivirus:** scans for and removes malware\n- **Backup:** copies data for safekeeping\n- **Compression:** reduces file sizes\n- **File manager:** organize and manage files\n\n## Open Source vs Proprietary\n\n### Open Source\n- Source code is freely available\n- Can be modified and redistributed\n- Examples: Linux, Android, LibreOffice\n- Free to use, community support\n\n### Proprietary (Closed Source)\n- Source code is kept secret\n- Cannot be modified without permission\n- Examples: Windows, macOS, Microsoft Office\n- Paid, company support`,
    questions: [
      { q: 'The OS manages:', opts: ['Hardware and software resources', 'Only the CPU', 'Only files', 'Internet connection'], correct: 1, explain: 'The OS is the interface between user, hardware, and software.' },
      { q: 'Memory management involves:', opts: ['Allocating RAM to programs', 'Connecting to WiFi', 'Playing audio', 'Saving files to disk'], correct: 1, explain: 'The OS decides which programs get which parts of RAM.' },
      { q: 'A device driver is:', opts: ['Software that lets OS communicate with hardware', 'A physical cable', 'A type of virus', 'A file format'], correct: 1, explain: 'Device drivers translate between the OS and specific hardware.' },
      { q: 'Disk defragmenter:', opts: ['Reorganizes files on disk for faster access', 'Deletes all files', 'Installs new programs', 'Increases RAM'], correct: 1, explain: 'Defragmentation puts related file pieces together, reducing seek time.' },
      { q: 'Linux is an example of:', opts: ['Open source software', 'Proprietary software', 'A hardware device', 'A protocol'], correct: 1, explain: 'Linux is open source — its code is freely available and modifiable.' },
      { q: 'Multitasking in an OS means:', opts: ['Running multiple programs by sharing CPU time', 'Having multiple monitors', 'Using multiple keyboards', 'Having multiple hard drives'], correct: 1, explain: 'The OS rapidly switches between programs, giving each some CPU time.' },
      { q: 'File management includes:', opts: ['Organizing files and controlling access permissions', 'Downloading files', 'Creating websites', 'Playing videos'], correct: 1, explain: 'The OS organizes, stores, and controls access to files.' },
      { q: 'An advantage of open source software is:', opts: ['Can be modified freely', 'Always has better graphics', 'Runs faster', 'Never has bugs'], correct: 1, explain: 'Open source allows anyone to view, modify, and redistribute the code.' },
      { q: 'A utility program is:', opts: ['A system tool that performs maintenance tasks', 'An operating system', 'A programming language', 'A web browser'], correct: 1, explain: 'Utilities include antivirus, defragmenter, backup tools, etc.' },
      { q: 'Security functions of an OS include:', opts: ['User authentication and access control', 'Making the screen brighter', 'Playing music', 'Connecting to WiFi'], correct: 1, explain: 'OS verifies user identity and controls who can access what.' }
    ]
  },
  {
    name: 'Database Systems',
    lesson: `# Database Systems\n\n## What is a Database?\nAn organised collection of structured data, stored electronically and managed by a Database Management System (DBMS).\n\n## Relational Databases\nData is stored in **tables** (relations) linked by common fields.\n\n### Key Terms\n- **Table:** a collection of related data (e.g., Students)\n- **Record (row):** one entry in a table (e.g., one student)\n- **Field (column):** a piece of data (e.g., name, age)\n- **Primary Key:** unique identifier for each record (e.g., StudentID)\n- **Foreign Key:** field that references the primary key of another table\n\n## Relationships\n- **One-to-One:** one record in A relates to one in B\n- **One-to-Many:** one record in A relates to many in B (most common)\n- **Many-to-Many:** many records in A relate to many in B\n\n## Normalisation\nOrganizing data to reduce redundancy and improve integrity.\n\n## SQL (Structured Query Language)\n\n### SELECT — Read data\n\`\`\`sql\nSELECT name, age FROM students WHERE age > 15;\n\`\`\`\n\n### INSERT — Add data\n\`\`\`sql\nINSERT INTO students (name, age) VALUES ('Ali', 16);\n\`\`\`\n\n### UPDATE — Modify data\n\`\`\`sql\nUPDATE students SET age = 17 WHERE name = 'Ali';\n\`\`\`\n\n### DELETE — Remove data\n\`\`\`sql\nDELETE FROM students WHERE name = 'Ali';\n\`\`\`\n\n### JOIN — Combine tables\n\`\`\`sql\nSELECT students.name, grades.grade\nFROM students\nINNER JOIN grades ON students.id = grades.student_id;\n\`\`\`\n\n### ORDER BY, LIMIT, LIKE\n\`\`\`sql\nSELECT * FROM students ORDER BY name ASC LIMIT 10;\nSELECT * FROM students WHERE name LIKE '%Ali%';\n\`\`\``,
    questions: [
      { q: 'In a database table, a row is called a:', opts: ['Record', 'Field', 'Column', 'Key'], correct: 1, explain: 'A row = record = one entry in the table.' },
      { q: 'A primary key is:', opts: ['A unique identifier for each record', 'The first field in a table', 'A password field', 'Any repeated field'], correct: 1, explain: 'Primary key uniquely identifies each record (no duplicates allowed).' },
      { q: 'Which SQL command reads data?', opts: ['SELECT', 'INSERT', 'UPDATE', 'DELETE'], correct: 1, explain: 'SELECT is used to retrieve/query data from a database.' },
      { q: 'A foreign key:', opts: ['Links two tables by referencing a primary key', 'Is always numeric', 'Must be unique', 'Is the first column'], correct: 1, explain: 'A foreign key in one table references the primary key of another.' },
      { q: 'INSERT INTO students (name) VALUES ("Sara") does what?', opts: ['Adds a new student named Sara', 'Deletes Sara', 'Updates Sara\'s name', 'Finds Sara'], correct: 1, explain: 'INSERT adds a new record to the table.' },
      { q: 'Which SQL keyword sorts results?', opts: ['ORDER BY', 'GROUP BY', 'SORT BY', 'ARRANGE BY'], correct: 1, explain: 'ORDER BY sorts results (ASC = ascending, DESC = descending).' },
      { q: 'A one-to-many relationship means:', opts: ['One record in A links to many in B', 'Many records in A link to one in B', 'All records are linked', 'No records are linked'], correct: 1, explain: 'One record in the "one" table relates to multiple in the "many" table.' },
      { q: 'SELECT * FROM students LIMIT 5 returns:', opts: ['First 5 records', 'All records', '5 columns', 'The 5th record only'], correct: 1, explain: 'LIMIT 5 restricts output to 5 rows.' },
      { q: 'Normalisation is used to:', opts: ['Reduce data redundancy', 'Increase file size', 'Speed up the internet', 'Format documents'], correct: 1, explain: 'Normalisation organizes data to avoid duplication and improve consistency.' },
      { q: 'An INNER JOIN returns:', opts: ['Only matching records from both tables', 'All records from both tables', 'Only records from the left table', 'No records'], correct: 1, explain: 'INNER JOIN returns only rows where the join condition matches in both tables.' }
    ]
  },
  {
    name: 'Programming Concepts',
    lesson: `# Programming Concepts\n\n## Variables and Assignment\n\`\`\`python\nname = "Ali"        # String\nage = 16             # Integer\ngpa = 3.75           # Float\nis_active = True     # Boolean\n\`\`\`\n\n## Selection (IF statements)\n\`\`\`python\nif score >= 90:\n    grade = "A"\nelif score >= 80:\n    grade = "B"\nelse:\n    grade = "C"\n\`\`\`\n\n## Iteration (Loops)\n\n### FOR loop\n\`\`\`python\nfor i in range(1, 11):\n    print(i)  # Prints 1 to 10\n\`\`\`\n\n### WHILE loop\n\`\`\`python\nwhile count > 0:\n    print(count)\n    count = count - 1\n\`\`\`\n\n## Lists/Arrays\n\`\`\`python\nfruits = ["apple", "banana", "cherry"]\nprint(fruits[0])    # "apple" (index 0)\nfruits.append("date") # Add element\nlen(fruits)          # Length\n\`\`\`\n\n## String Manipulation\n\`\`\`python\ntext = "Hello World"\ntext.upper()        # "HELLO WORLD"\ntext.lower()        # "hello world"\ntext[0:5]           # "Hello" (slicing)\ntext.replace("World", "Python")\nlen(text)           # 11\n\`\`\`\n\n## Procedures and Functions\n\`\`\`python\ndef greet(name):        # Function with parameter\n    return "Hello " + name\n\ndef print_menu():       # Procedure (no return)\n    print("1. Start")\n    print("2. Quit")\n\`\`\`\n\n## File Handling\n\`\`\`python\n# Writing\nwith open("data.txt", "w") as f:\n    f.write("Hello")\n\n# Reading\nwith open("data.txt", "r") as f:\n    content = f.read()\n\`\`\`\n\n## Exception Handling\n\`\`\`python\ntry:\n    result = 10 / number\nexcept ZeroDivisionError:\n    print("Cannot divide by zero")\n\`\`\`\n\n## Debugging\n- **Syntax errors:** code violates language rules (missing colon, bracket)\n- **Runtime errors:** code crashes during execution (divide by zero)\n- **Logic errors:** code runs but produces wrong output\n\nDebugging methods: print statements, step-through, breakpoints, testing with known values`,
    questions: [
      { q: 'In most languages, array indexing starts at:', opts: ['0', '1', '-1', '2'], correct: 1, explain: 'Arrays are zero-indexed — first element is at index 0.' },
      { q: 'What will this print? x = 5; x += 3', opts: ['8', '53', '5', '3'], correct: 1, explain: 'x += 3 means x = x + 3 = 5 + 3 = 8.' },
      { q: 'A function that returns a value uses the keyword:', opts: ['return', 'print', 'yield', 'output'], correct: 1, explain: 'The return statement sends a value back to the caller.' },
      { q: 'A logic error is when:', opts: ['The program runs but gives wrong output', 'The program won\'t compile', 'The program crashes', 'The keyboard stops working'], correct: 1, explain: 'Logic errors produce incorrect results without crashing.' },
      { q: 'What does len("Python") return?', opts: ['6', '5', '7', '1'], correct: 1, explain: '"Python" has 6 characters (P-y-t-h-o-n).' },
      { q: 'Which loop runs at least once?', opts: ['WHILE', 'REPEAT...UNTIL', 'FOR', 'DO...WHILE'], correct: 1, explain: 'REPEAT...UNTIL (or DO...WHILE) tests condition at the end.' },
      { q: 's = "Hello"; s[1:4] gives:', opts: ['"ell"', '"Hello"', '"Hel"', '"ello"'], correct: 1, explain: 's[1:4] extracts characters at indices 1, 2, 3 = "ell".' },
      { q: 'A variable is:', opts: ['A named storage that can change value', 'A fixed constant', 'A function', 'An input device'], correct: 1, explain: 'A variable stores data that can be modified during execution.' },
      { q: 'Which is a syntax error?', opts: ['Missing colon after if statement', 'Dividing by zero', 'Wrong calculation formula', 'Typo in a variable name'], correct: 1, explain: 'Syntax errors violate the language rules — the code won\'t even run.' },
      { q: 'try/except is used for:', opts: ['Handling errors (exceptions)', 'Creating loops', 'Defining variables', 'Importing modules'], correct: 1, explain: 'try/except blocks catch and handle runtime errors gracefully.' }
    ]
  },
  {
    name: 'Ethics, Security & Impact',
    lesson: `# Ethics, Security & Impact\n\n## Legal Issues\n\n### Data Protection Act (UK)\n- Personal data must be collected, stored, and used fairly and lawfully\n- Data should only be used for its intended purpose\n- Data must be accurate and up-to-date\n- People have the right to see their data\n- Data must be kept secure\n\n### Computer Misuse Act (UK)\n- **Unauthorised access** to computer systems is illegal\n- **Unauthorised modification** of data is illegal\n- **Hacking** and creating/distributing malware is illegal\n- Penalties include fines and imprisonment\n\n### Copyright Law\n- Software, music, films, and books are protected by copyright\n- Copying without permission is illegal\n- Covers: programs, apps, websites, digital content\n\n## Ethical Issues\n- **Privacy:** Should companies collect so much personal data?\n- **Surveillance:** CCTV, tracking, monitoring employees\n- **Digital divide:** Not everyone has equal access to technology\n- **Job displacement:** Automation replacing human workers\n- **Addiction:** Social media, gaming, screen time\n- **Misinformation:** Fake news, deepfakes\n\n## Environmental Impact\n- **E-waste:** Discarded electronics contain toxic materials (lead, mercury)\n- **Energy consumption:** Data centres use massive amounts of electricity\n- **Carbon footprint:** Manufacturing, transport, and disposal of tech\n- **Positive:** Remote working reduces travel, smart grids save energy\n\n## Health and Safety\n- **RSI (Repetitive Strain Injury):** from repetitive keyboard/mouse use\n- **Eye strain:** from prolonged screen use (20-20-20 rule)\n- **Posture problems:** poor desk setup\n- **Radiation:** from screens (low risk, mostly debunked)\n- Solutions: regular breaks, ergonomic equipment, proper lighting\n\n## Security Measures\n- **Encryption:** scramble data so only authorized people can read it\n- **Firewall:** blocks unauthorized network access\n- **Antivirus:** detects and removes malware\n- **Strong passwords:** long, complex, unique\n- **Two-factor authentication:** password + phone code\n- **Access controls:** permissions for different users\n- **Regular backups:** protect against data loss\n- **Updates/patches:** fix security vulnerabilities`,
    questions: [
      { q: 'The Data Protection Act requires personal data to be:', opts: ['Stored securely and used fairly', 'Shared with everyone', 'Made public', 'Deleted after 1 year'], correct: 1, explain: 'DPA requires fair, lawful, secure handling of personal data.' },
      { q: 'Hacking into a computer system is illegal under:', opts: ['Computer Misuse Act', 'Data Protection Act', 'Copyright Law', 'Health and Safety Act'], correct: 1, explain: 'The Computer Misuse Act makes unauthorised access illegal.' },
      { q: 'What is RSI?', opts: ['Repetitive Strain Injury from computer use', 'Remote Server Interface', 'Random Signal Interference', 'Rapid System Installation'], correct: 1, explain: 'RSI = Repetitive Strain Injury, caused by repetitive movements like typing.' },
      { q: 'The 20-20-20 rule helps prevent:', opts: ['Eye strain', 'RSI', 'Back pain', 'Headaches'], correct: 1, explain: 'Every 20 minutes, look at something 20 feet away for 20 seconds.' },
      { q: 'Two-factor authentication uses:', opts: ['Password + another verification method', 'Two passwords', 'Two usernames', 'Two computers'], correct: 1, explain: '2FA = something you know (password) + something you have (phone code).' },
      { q: 'Copyright law protects:', opts: ['Digital content from unauthorized copying', 'Physical hardware', 'Network cables', 'Operating systems only'], correct: 1, explain: 'Copyright covers software, music, films, books, and other creative works.' },
      { q: 'A positive environmental impact of technology is:', opts: ['Remote working reduces travel emissions', 'More electricity usage', 'More e-waste', 'Larger data centres'], correct: 1, explain: 'Remote work means less commuting → fewer car emissions.' },
      { q: 'E-waste is problematic because it contains:', opts: ['Toxic materials like lead and mercury', 'Valuable gold only', 'Recyclable paper', 'Biodegradable materials'], correct: 1, explain: 'Electronics contain toxic chemicals that harm the environment if not disposed of properly.' },
      { q: 'Encryption is used to:', opts: ['Scramble data so only authorised people can read it', 'Make files larger', 'Speed up downloads', 'Create backup copies'], correct: 1, explain: 'Encryption converts readable data into coded form, readable only with the key.' },
      { q: 'The digital divide refers to:', opts: ['Unequal access to technology between groups', 'Two computer screens', 'A gap in software versions', 'A firewall setting'], correct: 1, explain: 'Some people/regions have much less access to technology and internet.' }
    ]
  },
  {
    name: 'Logic Gates & Boolean Logic',
    lesson: `# Logic Gates & Boolean Logic\n\n## Boolean Logic\nUses only two values: TRUE (1) and FALSE (0)\n\n## Logic Gates\n\n### AND Gate\n| A | B | Output |\n|---|---|--------|\n| 0 | 0 | 0 |\n| 0 | 1 | 0 |\n| 1 | 0 | 0 |\n| 1 | 1 | 1 |\nOutput is 1 ONLY when BOTH inputs are 1.\n\n### OR Gate\n| A | B | Output |\n|---|---|--------|\n| 0 | 0 | 0 |\n| 0 | 1 | 1 |\n| 1 | 0 | 1 |\n| 1 | 1 | 1 |\nOutput is 1 when AT LEAST ONE input is 1.\n\n### NOT Gate (Inverter)\n| Input | Output |\n|-------|--------|\n| 0 | 1 |\n| 1 | 0 |\nReverses the input.\n\n### XOR Gate (Exclusive OR)\n| A | B | Output |\n|---|---|--------|\n| 0 | 0 | 0 |\n| 0 | 1 | 1 |\n| 1 | 0 | 1 |\n| 1 | 1 | 0 |\nOutput is 1 when inputs are DIFFERENT.\n\n### NAND Gate (NOT AND)\n| A | B | Output |\n|---|---|--------|\n| 0 | 0 | 1 |\n| 0 | 1 | 1 |\n| 1 | 0 | 1 |\n| 1 | 1 | 0 |\nOutput is the opposite of AND.\n\n## Combining Gates\nComplex logic circuits are built by combining basic gates.\n\n**Example:** A burglar alarm that activates when: motion detected AND it's nighttime\n= MotionSensor AND NightSensor → Alarm\n\n**Example:** A light that turns on when: switch A OR switch B is pressed\n= SwitchA OR SwitchB → Light`,
    questions: [
      { q: 'AND gate output when A=1, B=0:', opts: ['0', '1', 'Unknown', '2'], correct: 1, explain: 'AND: output 1 only when BOTH inputs are 1. 1 AND 0 = 0.' },
      { q: 'OR gate output when A=0, B=1:', opts: ['1', '0', 'Unknown', '2'], correct: 1, explain: 'OR: output 1 when AT LEAST ONE input is 1. 0 OR 1 = 1.' },
      { q: 'NOT gate with input 1 gives:', opts: ['0', '1', '2', '-1'], correct: 1, explain: 'NOT inverts: 1 → 0.' },
      { q: 'XOR gate output when A=1, B=1:', opts: ['0', '1', '2', 'Unknown'], correct: 1, explain: 'XOR: output 0 when inputs are the SAME. 1 XOR 1 = 0.' },
      { q: 'A NAND gate is equivalent to:', opts: ['NOT followed by AND', 'AND followed by NOT', 'OR followed by NOT', 'NOT followed by OR'], correct: 1, explain: 'NAND = NOT(AND) — AND gate followed by NOT gate.' },
      { q: 'Which gate gives output 1 only when inputs differ?', opts: ['XOR', 'AND', 'OR', 'NAND'], correct: 1, explain: 'XOR (Exclusive OR) outputs 1 only when inputs are different.' },
      { q: 'How many rows in a truth table for 3 inputs?', opts: ['8', '4', '6', '16'], correct: 1, explain: '2³ = 8 rows for 3 inputs.' },
      { q: 'AND gate truth table: output is 1 only when:', opts: ['Both inputs are 1', 'At least one input is 1', 'Both inputs are 0', 'Inputs are different'], correct: 1, explain: 'AND requires BOTH inputs to be 1.' },
      { q: 'OR gate output when A=0, B=0:', opts: ['0', '1', '2', 'Unknown'], correct: 1, explain: '0 OR 0 = 0 (no inputs are 1).' },
      { q: 'A half adder adds two binary digits and produces:', opts: ['Sum and Carry', 'Sum only', 'Carry only', 'Product'], correct: 1, explain: 'Half adder: Sum = A XOR B, Carry = A AND B.' }
    ]
  },
  {
    name: 'Web Technologies',
    lesson: `# Web Technologies\n\n## How the Web Works\n1. User enters URL in browser\n2. Browser sends HTTP request to web server\n3. Server processes request and sends back HTML/CSS/JS\n4. Browser renders the page\n\n## HTML (HyperText Markup Language)\nDefines the **structure** of a web page.\n\n\`\`\`html\n<html>\n<head><title>My Page</title></head>\n<body>\n  <h1>Hello World</h1>\n  <p>This is a paragraph.</p>\n</body>\n</html>\n\`\`\`\n\n## CSS (Cascading Style Sheets)\nDefines the **appearance** — colours, fonts, layout.\n\n\`\`\`css\nh1 { color: blue; font-size: 24px; }\n\`\`\`\n\n## JavaScript\nAdds **interactivity** — buttons, animations, dynamic content.\n\n\`\`\`javascript\ndocument.getElementById("btn").onclick = function() {\n  alert("Clicked!");\n};\n\`\`\`\n\n## Client-Server Model\n- **Client:** user's browser (sends requests)\n- **Server:** powerful computer that stores the website (sends responses)\n- **Database:** stores data on the server\n\n## HTTP Methods\n- **GET:** retrieve data (loading a page)\n- **POST:** send data (submitting a form)\n\n## Status Codes\n- **200:** OK (success)\n- **301:** Moved permanently (redirect)\n- **404:** Not found\n- **500:** Internal server error\n\n## Search Engine Optimisation (SEO)\nMaking websites appear higher in search results:\n- Relevant keywords in content\n- Good page titles and descriptions\n- Fast loading speed\n- Mobile-friendly design\n- Quality backlinks`,
    questions: [
      { q: 'HTML defines the:', opts: ['Structure of a web page', 'Appearance', 'Interactivity', 'Database'], correct: 1, explain: 'HTML provides the structure (headings, paragraphs, links).' },
      { q: 'CSS is used for:', opts: ['Styling and appearance', 'Page structure', 'Database queries', 'File management'], correct: 1, explain: 'CSS controls colours, fonts, layout, and visual design.' },
      { q: 'JavaScript adds:', opts: ['Interactivity to web pages', 'Database storage', 'Network connections', 'File compression'], correct: 1, explain: 'JavaScript makes pages dynamic — buttons, animations, form validation.' },
      { q: 'HTTP status code 404 means:', opts: ['Page not found', 'Success', 'Server error', 'Redirect'], correct: 1, explain: '404 = the requested page could not be found on the server.' },
      { q: 'The GET method is used to:', opts: ['Retrieve data from the server', 'Send form data', 'Delete data', 'Update the database'], correct: 1, explain: 'GET requests data (e.g., loading a webpage).' },
      { q: 'A web server is:', opts: ['A computer that stores and serves web pages', 'A browser', 'A printer', 'A monitor'], correct: 1, explain: 'The web server stores website files and responds to requests.' },
      { q: 'In the client-server model, the client is:', opts: ['The user\'s browser', 'The web server', 'The database', 'The router'], correct: 1, explain: 'The client sends requests; the server sends responses.' },
      { q: 'SEO helps websites:', opts: ['Rank higher in search results', 'Load faster', 'Use less memory', 'Avoid viruses'], correct: 1, explain: 'SEO improves visibility in search engines like Google.' },
      { q: 'HTTP status 200 means:', opts: ['OK / success', 'Not found', 'Server error', 'Redirect'], correct: 1, explain: '200 = the request was successful.' },
      { q: 'Which is NOT a programming language used on the web?', opts: ['C++', 'HTML', 'CSS', 'JavaScript'], correct: 1, explain: 'HTML is a markup language, not a programming language (though used on the web).' }
    ]
  },
  {
    name: 'Robotics & AI',
    lesson: `# Robotics & AI\n\n## What is AI (Artificial Intelligence)?\nComputer systems that can perform tasks normally requiring human intelligence.\n\n## Types of AI\n\n### Machine Learning\n- Systems that learn from data without being explicitly programmed\n- **Supervised learning:** trained on labelled data\n- **Unsupervised learning:** finds patterns in unlabelled data\n- **Reinforcement learning:** learns through trial and error with rewards\n\n### Expert Systems\n- Computer programs that mimic human expert decision-making\n- Use a knowledge base and inference rules\n- Examples: medical diagnosis, financial advice\n\n## Robotics\n- Robots are programmable machines that can carry out tasks autonomously or semi-autonomously\n\n### Types of Robots\n- **Industrial:** assembly lines, manufacturing\n- **Medical:** surgical robots, rehabilitation\n- **Service:** vacuum cleaners, lawnmowers\n- **Exploration:** space rovers, deep-sea robots\n- **Social:** humanoid robots, chatbots\n\n### Robot Components\n- **Sensors:** detect environment (cameras, microphones, touch, temperature)\n- **Actuators:** move parts (motors, servos)\n- **Controller:** processes data and makes decisions (CPU/microcontroller)\n- **Power supply:** battery or mains\n\n## Applications of AI and Robotics\n- **Healthcare:** diagnosis, drug discovery, surgery\n- **Transport:** self-driving cars, drones\n- **Finance:** fraud detection, algorithmic trading\n- **Manufacturing:** quality control, automation\n- **Education:** personalised learning, marking\n- **Entertainment:** game AI, music generation\n\n## Ethical Considerations\n- **Job loss:** robots replacing human workers\n- **Bias:** AI trained on biased data makes biased decisions\n- **Privacy:** surveillance and data collection\n- **Autonomy:** who is responsible when AI makes a mistake?\n- **Safety:** self-driving car accidents\n- **Control:** how much decision-making should we give to AI?`,
    questions: [
      { q: 'Machine learning is when:', opts: ['Systems learn from data without explicit programming', 'Humans teach computers step by step', 'Computers are manually programmed for each task', 'Robots physically learn from humans'], correct: 1, explain: 'ML systems find patterns in data and improve without explicit instructions.' },
      { q: 'An expert system mimics:', opts: ['Human expert decision-making', 'A robot\'s movement', 'A database query', 'An operating system'], correct: 1, explain: 'Expert systems use a knowledge base to replicate expert reasoning.' },
      { q: 'Which is a sensor used by robots?', opts: ['Camera', 'Motor', 'Battery', 'Processor'], correct: 1, explain: 'Cameras (and other sensors) let robots perceive their environment.' },
      { q: 'An ethical issue with AI is:', opts: ['Algorithmic bias from training data', 'AI being too slow', 'Robots using too little power', 'Software being too simple'], correct: 1, explain: 'AI trained on biased data produces biased outcomes.' },
      { q: 'Self-driving cars use:', opts: ['AI, sensors, and machine learning', 'Only GPS', 'Manual controls', 'Remote human operators only'], correct: 1, explain: 'Self-driving cars combine AI, cameras, lidar, GPS, and ML.' },
      { q: 'Reinforcement learning works by:', opts: ['Trial and error with reward signals', 'Being given labelled examples', 'Copying a human teacher', 'Random guessing forever'], correct: 1, explain: 'The system tries actions and gets rewards/penalties, learning the best strategy.' },
      { q: 'A robot actuator is:', opts: ['A device that moves parts (motor/servo)', 'A sensor', 'A battery', 'A camera'], correct: 1, explain: 'Actuators (motors, servos) are the "muscles" that make robots move.' },
      { q: 'AI in healthcare can be used for:', opts: ['Diagnosis, drug discovery, surgery', 'Only making coffee', 'Only playing games', 'Only cleaning floors'], correct: 1, explain: 'AI assists doctors with diagnosis, helps discover drugs, and guides surgical robots.' },
      { q: 'A concern about robots replacing workers is:', opts: ['Job displacement', 'Robots being too quiet', 'Robots using too much paint', 'Robots having too many sensors'], correct: 1, explain: 'Automation can replace human jobs, causing unemployment.' },
      { q: 'Unsupervised learning involves:', opts: ['Finding patterns in unlabelled data', 'Training on labelled examples', 'Human supervision at all times', 'Only classified data'], correct: 1, explain: 'Unsupervised learning finds hidden patterns without pre-labels.' }
    ]
  }
];

async function main() {
  const SUBJECT_LEVEL_ID = '30f51f6c-3ca4-4b2c-86b7-2b9a74d8ecba'; // CS O Level
  let topicCount = 0, questionCount = 0;

  for (const topic of topics) {
    topicCount++;
    console.log(`\n=== Topic ${topicCount}/${topics.length}: ${topic.name} ===`);

    const tr = await query(`INSERT INTO topics (subject_level_id, name, description, sort_order, created_at) VALUES ('${SUBJECT_LEVEL_ID}', ${esc(topic.name)}, ${esc(topic.name + ' - IGCSE Computer Science')}, ${topicCount}, now()) RETURNING id`);
    const tid = tr.rows ? tr.rows[0].id : tr[0]?.id;

    await query(`INSERT INTO lessons (topic_id, title, content, sort_order, created_at) VALUES ('${tid}', ${esc(topic.name)}, ${esc(topic.lesson)}, 1, now())`);

    const qr = await query(`INSERT INTO quizzes (topic_id, title, description, is_published, created_at) VALUES ('${tid}', ${esc(topic.name + ' Quiz')}, ${esc('Test your knowledge of ' + topic.name)}, true, now()) RETURNING id`);
    const qid = qr.rows ? qr.rows[0].id : qr[0]?.id;

    for (let i = 0; i < topic.questions.length; i++) {
      const q = topic.questions[i];
      await query(`INSERT INTO questions (quiz_id, question_text, options, correct_option, explanation, sort_order, created_at) VALUES ('${qid}', ${esc(q.q)}, '${JSON.stringify(q.opts)}', ${q.correct}, ${esc(q.explain)}, ${i + 1}, now())`);
      questionCount++;
    }
    console.log(`  ✓ ${topic.questions.length} questions`);
  }

  console.log(`\n=== DONE: ${topicCount} topics, ${topicCount} lessons, ${topicCount} quizzes, ${questionCount} questions ===`);
}

main().catch(console.error);
