-- Ingest the 2025 Feb/Mar exam sittings the recurring link check flagged.
--
-- The past-papers-harvest job records a newly-published sitting it has no
-- archive row for as a slot='candidate' row. Approving one through the admin
-- panel only creates a hidden, untagged draft per *file*, which is not the
-- archive's shape (one row per paper, carrying both the question paper and its
-- mark scheme), so this migration lands the real rows.
--
-- Each row below clones the metadata (title, paper_number, topic_id,
-- subject_slug, level, source_url) of the newest existing sibling row for that
-- paper, then attaches the question paper and mark scheme downloaded from the
-- candidate's recorded source and uploaded to the private past-papers bucket
-- (23 rows, 46 files).
--
-- Generated by .freebuff/pp-candidates-ingest.cjs.

begin;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '4814d57d-4628-478b-9a45-72e2de13d742', 'Cambridge IGCSE Computer Science 0478 — Paper 1: Computer Systems (0478/12)', 2025, 'Feb/Mar', 'Paper 1 (12)', '3aef5c79-5146-499d-b4ce-b7118005ffe7', 'computer-science', 'OL'::subject_level, 'papers/2dd49c11-944f-4a24-b216-fcff9dbb7e91.pdf', 'mark-schemes/1a99f277-b3e9-4ccd-b718-20a5a17a9012.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-computer-science-0478/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'b71f511e-f12f-4ab2-a988-4d5401d706a7', 'Cambridge IGCSE Computer Science 0478 — Paper 2: Algorithms, Programming and Logic (0478/22)', 2025, 'Feb/Mar', 'Paper 2 (22)', '35378b08-5638-4278-84b4-def6b1041f0a', 'computer-science', 'OL'::subject_level, 'papers/21e37291-cca8-416d-a5c7-a0ff9d87fd0d.pdf', 'mark-schemes/7bf859b8-7365-4b33-848f-6da895d420f4.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-computer-science-0478/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '2e893734-ab26-419e-95b9-39b6c144c422', 'Cambridge IGCSE Maths 0580 — Paper 1: Core (0580/12)', 2025, 'Feb/Mar', 'Paper 1 (12)', '71c9573e-0ab6-40e9-89c7-9f5a68410548', 'mathematics', 'OL'::subject_level, 'papers/3dc28194-58ee-4766-8fd7-2de4ea747ecc.pdf', 'mark-schemes/0c5045db-bdf9-490d-b7d5-353dc5f223aa.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-mathematics-0580/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '982e998e-8596-480b-888a-13f720a87b46', 'Cambridge IGCSE Maths 0580 — Paper 2: Extended (0580/22)', 2025, 'Feb/Mar', 'Paper 2 (22)', '0bea2707-6672-4f20-8be1-a847f759f0ca', 'mathematics', 'OL'::subject_level, 'papers/8c4ed87c-b0e6-4f57-b7da-1a686b533d19.pdf', 'mark-schemes/4adcf1a2-2f36-4607-a5cf-645df718c292.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-mathematics-0580/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '3bf0aff1-0d5d-4469-a22b-e4d9be8cf2e7', 'Cambridge IGCSE Maths 0580 — Paper 3: Core (0580/32)', 2025, 'Feb/Mar', 'Paper 3 (32)', '2e24998f-13bf-4bd7-815c-0c822640fa94', 'mathematics', 'OL'::subject_level, 'papers/b2aa1107-0e82-42c2-9712-cf01438e48fb.pdf', 'mark-schemes/1d7b12b0-9687-4a7c-93f9-d0974e33f37f.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-mathematics-0580/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'ed3d9f20-d6a4-425e-95cc-547493c301d7', 'Cambridge IGCSE Maths 0580 — Paper 4: Extended (0580/42)', 2025, 'Feb/Mar', 'Paper 4 (42)', '4a093751-70de-4b7b-a451-94efe48c280c', 'mathematics', 'OL'::subject_level, 'papers/1d337f10-628a-4c3a-89cd-973694326895.pdf', 'mark-schemes/81e24160-ddb1-40f6-a24e-9242c6eff2be.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-mathematics-0580/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '07ed1a0b-c9fb-4cc6-95d7-66e5b4c24ce8', 'Edexcel IAL Maths — Mechanics M1 (WME01/01)', 2025, 'Feb/Mar', 'Paper 4 (12)', 'ebe3caea-37e6-47ae-ba8e-1a5cb713196b', 'mathematics', 'AS'::subject_level, 'papers/ba4e23b1-a5aa-437c-8309-2aa8485cf0c4.pdf', 'mark-schemes/d9cefabe-7d23-4b62-9f73-b8d86f41b18a.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/mathematics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '8ec5ba15-0e02-49f9-84a7-0db320698431', 'Edexcel IAL Maths — Pure Mathematics P1 (WMA11/01)', 2025, 'Feb/Mar', 'Paper 1 (12)', '5883f323-f4cd-4741-a6bc-a9c051b11ebf', 'mathematics', 'AS'::subject_level, 'papers/45ebd604-128a-434b-9046-5a4c68082489.pdf', 'mark-schemes/16d807fd-f273-4083-9271-c99568f8a6d6.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/mathematics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '6e6aa778-0a12-4e27-8655-d54ac472f3b4', 'Edexcel IAL Maths — Pure Mathematics P2 (WMA12/01)', 2025, 'Feb/Mar', 'Paper 2 (12)', 'cd2ded77-54dc-4b5f-8f4f-a066f9b40184', 'mathematics', 'A2'::subject_level, 'papers/4ccec3fa-2d6e-4568-ac95-4d881446d21f.pdf', 'mark-schemes/de856016-f513-4f9a-827d-e6ce1423a3a4.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/mathematics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '0f2ea33f-c4b5-4024-991d-b0fad2af0d1f', 'Edexcel IAL Maths — Pure Mathematics P3 (WMA13/01)', 2025, 'Feb/Mar', 'Paper 3 (12)', '4a4ae03f-b502-41f7-8136-209e2a811174', 'mathematics', 'A2'::subject_level, 'papers/9e5f3b9d-c8d0-40f7-a081-7dc57aaf9db1.pdf', 'mark-schemes/bdcad089-fd59-4df9-8880-68b80ab01f72.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/mathematics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'aa7b8637-66c1-4b8d-a317-48fa22fbb241', 'Edexcel IAL Maths — Statistics S1 (WST01/01)', 2025, 'Feb/Mar', 'Paper 5 (12)', '5883f323-f4cd-4741-a6bc-a9c051b11ebf', 'mathematics', 'AS'::subject_level, 'papers/0b0d25e9-e452-47bc-bb64-efdc2de8d651.pdf', 'mark-schemes/f3559a5d-659c-4628-8a0a-665b882f0a4b.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/mathematics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '8927cc29-1da9-42a7-9311-5a1e30a7941a', 'Edexcel IAL Maths — Statistics S2 (WST02/01)', 2025, 'Feb/Mar', 'Paper 6 (12)', '3e08bf8f-4227-40a9-b6af-783b81e8b31f', 'mathematics', 'A2'::subject_level, 'papers/df91247f-8daa-4526-9f4f-b7af0ae31772.pdf', 'mark-schemes/f571c6c9-e55e-4979-8a97-af6dcaa53cc4.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/mathematics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'a05b87fe-a954-4b4b-bf98-bf234f9658de', 'Cambridge IGCSE Physics 0625 — Paper 1: Multiple Choice Core (0625/12)', 2025, 'Feb/Mar', 'Paper 1 (12)', '4d916da8-2ce0-46a4-9af9-bc20b007cc91', 'physics', 'OL'::subject_level, 'papers/dbe58ee4-0b8f-4ff1-b6a9-e1e72b2789ab.pdf', 'mark-schemes/ec01b519-7091-43d4-b03c-78234175dcc5.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '3381df69-69cb-406d-a501-12d029c16925', 'Cambridge IGCSE Physics 0625 — Paper 2: Multiple Choice Extended (0625/22)', 2025, 'Feb/Mar', 'Paper 2 (22)', '4fbcf844-f1cc-41c3-a81d-e4dba7ad964b', 'physics', 'OL'::subject_level, 'papers/9232eb9b-d33d-426c-b220-a30c68b8e19a.pdf', 'mark-schemes/6127f7e7-1aa8-4bf9-a876-bb0935e8a7f6.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'ff5ec77e-9cdc-413c-87ed-cb7f9383cd80', 'Cambridge IGCSE Physics 0625 — Paper 3: Theory Core (0625/32)', 2025, 'Feb/Mar', 'Paper 3 (32)', '50490955-308d-4170-b70a-697d18aaec9f', 'physics', 'OL'::subject_level, 'papers/813e6c8b-926a-4f9e-94e4-e387e58c1701.pdf', 'mark-schemes/739fe9e0-6d6a-4595-8edd-636c739f329f.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'd49a06b3-4b6a-4b8e-87b3-4e0189e656a6', 'Cambridge IGCSE Physics 0625 — Paper 4: Theory Extended (0625/42)', 2025, 'Feb/Mar', 'Paper 4 (42)', '3cbd0390-fca7-434d-aa02-241ce0947848', 'physics', 'OL'::subject_level, 'papers/1fc1a4a3-95e7-4cd4-a674-290e1caa0f78.pdf', 'mark-schemes/34fd5e5f-349b-401b-a404-47fbdb2c44d7.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '9524adcc-f32a-434e-89b7-be2edd0175fd', 'Cambridge IGCSE Physics 0625 — Paper 5: Practical Test (0625/52)', 2025, 'Feb/Mar', 'Paper 5 (52)', '39682f0d-d101-4e70-8f91-05961d6c2a80', 'physics', 'OL'::subject_level, 'papers/8fad1004-d690-4cdf-8448-c3037d7e45a3.pdf', 'mark-schemes/7c52af8c-d31b-4c68-8f8d-34d8a7e8d82e.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'df6c8bc6-4c47-4e23-acdc-55a6e020eb60', 'Cambridge IGCSE Physics 0625 — Paper 6: Alternative to Practical (0625/62)', 2025, 'Feb/Mar', 'Paper 6 (62)', '35b1da75-be47-4c45-8751-9a70ae75875a', 'physics', 'OL'::subject_level, 'papers/1972e046-f487-4cb4-aee7-1ffcc701fdc6.pdf', 'mark-schemes/997d8513-353b-4f08-a487-6b40fab80351.pdf', 'https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/past-papers/'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '71c494a6-9a08-4eb1-af50-8b3ee8f4a91b', 'Edexcel IAL Physics — Unit 1: Mechanics and Materials (WPH11/01)', 2025, 'Feb/Mar', 'Paper 1 (12)', '15a26a2d-cb1f-4059-810f-1698500fe548', 'physics', 'AS'::subject_level, 'papers/03b313ca-9e7f-4633-a18e-3f6d25ac18fb.pdf', 'mark-schemes/dcc7ef4c-68df-4653-a917-9f246b9e0024.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/physics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '787c1da2-87e3-45a5-9828-60e5f116f975', 'Edexcel IAL Physics — Unit 2: Waves and Electricity (WPH12/01)', 2025, 'Feb/Mar', 'Paper 2 (12)', '15a26a2d-cb1f-4059-810f-1698500fe548', 'physics', 'AS'::subject_level, 'papers/44a24a82-29c0-42e7-96dd-6f1cf7d11ea8.pdf', 'mark-schemes/4c36d62f-833f-47aa-b02f-4b99ee135f46.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/physics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  '0bf7000e-1e3c-4b73-8b5a-40cb326cdda4', 'Edexcel IAL Physics — Unit 3: Practical Skills in Physics I (WPH13/01)', 2025, 'Feb/Mar', 'Paper 3 (12)', '15a26a2d-cb1f-4059-810f-1698500fe548', 'physics', 'AS'::subject_level, 'papers/f0f0eae7-9592-43d2-8fcc-ad4594d00711.pdf', 'mark-schemes/9bc54998-9e01-4032-8cce-7e02235e67c9.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/physics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'a201517b-1896-417d-8e3e-82fbea1c78c9', 'Edexcel IAL Physics — Unit 4: Further Mechanics, Fields and Particles (WPH14/01)', 2025, 'Feb/Mar', 'Paper 4 (12)', '33144da3-195d-4c11-b5f8-a1c05eec5286', 'physics', 'A2'::subject_level, 'papers/67e332cd-3946-41d4-a677-16d1618be8b7.pdf', 'mark-schemes/44f6498b-64ed-4aed-a73f-2126e766fb48.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/physics-2018.coursematerials.html'
) on conflict (id) do nothing;

insert into public.past_papers (id, title, year, session, paper_number, topic_id, subject_slug, level, paper_url, mark_scheme_url, source_url) values (
  'd1dddf25-1c29-4872-bfc1-50c01b6c980c', 'Edexcel IAL Physics — Unit 5: Thermodynamics, Radiation, Oscillations (WPH15/01)', 2025, 'Feb/Mar', 'Paper 5 (12)', '9c985dc8-bbb0-4506-9dfc-2f49b774fc24', 'physics', 'A2'::subject_level, 'papers/2ab1561c-ac86-44b3-b0b6-461d1ab78aad.pdf', 'mark-schemes/0fc6c9de-7144-4d3f-a822-9b139769ee5e.pdf', 'https://qualifications.pearson.com/en/qualifications/edexcel-international-advanced-levels/physics-2018.coursematerials.html'
) on conflict (id) do nothing;

-- The candidate checks that produced these rows are now resolved.
update public.past_paper_link_checks
   set review_status = 'approved', reviewed_at = now()
 where slot = 'candidate'
   and review_status in ('pending', 'approved')
   and source in ('pmt-harvest');

-- Untagged drafts left by earlier partial approvals; superseded by the rows above.
delete from public.past_papers where id in ('e49ccc52-6e35-4597-8109-70733882fafc','211acf8d-e662-46b8-adeb-b3c2a73db816','7f368fed-4384-492b-8c63-70ff78b27031','957e8264-815f-4f07-a5ca-43799dbf8fce','f57791f7-9d18-4a2c-8851-b5713c51b0fc','0378d6d8-8229-4f40-9e14-e8a20af44acb','61e2bf84-d4bf-4656-bfc6-c865dc2f53fb');

commit;
